import type { AiMlModel } from '../../types';

/**
 * Q-Learning — the reinforcement-learning stress test for this schema.
 *
 * Exercises ObjectiveKind 'fixed-point': there is no loss being minimized over
 * a dataset at all. The target moves as the estimate improves, and convergence
 * is to a fixed point of the Bellman operator. Any schema assuming
 * "loss, minimized over i.i.d. samples" breaks here, which is why this entry
 * was chosen to validate the shape before bulk authoring.
 */
export const Q_LEARNING: AiMlModel = {
  slug: 'q-learning',
  name: 'Q-Learning',
  aliases: ['Off-policy TD control', 'Watkins Q-learning'],
  category: 'reinforcement-learning',
  group: 'value-based',
  kind: 'model',

  paradigms: ['reinforcement'],
  taskTypes: ['control'],

  intuition:
    'Keep a table of "how good is taking action a in state s", then wander the environment updating each entry toward the reward you just got plus the best value you think is available from wherever you landed. The bootstrapping is the whole trick: you never wait to see how the episode ends, you update toward your own current estimate of the future. Do that enough times and the estimates converge on the truth — and acting greedily on them is the optimal policy.',

  objective: {
    kind: 'fixed-point',
    expression: {
      formula:
        'Q^{*}(s,a) = \\mathbb{E}\\Bigl[ r + \\gamma \\max_{a\'} Q^{*}(s\',a\') \;\\Big|\; s, a \\Bigr]',
      symbols: [
        { symbol: 'Q^{*}(s,a)', meaning: 'optimal action-value — expected discounted return from taking a in s, then acting optimally' },
        { symbol: '\\gamma \\in [0,1)', meaning: 'discount factor; how much a reward one step later is worth' },
        { symbol: 'r', meaning: 'immediate reward observed on this transition' },
        { symbol: '\\max_{a\'}', meaning: 'the greedy max that makes this OFF-policy — it ignores what the agent actually did next' },
      ],
    },
    reading:
      'This is not a loss to minimize over a dataset — it is a self-consistency condition. Q is correct exactly when it equals its own one-step lookahead. The Bellman operator is a gamma-contraction, so repeatedly applying it drives any starting table toward the unique fixed point. Naming this correctly matters: calling it a "loss function" would suggest a fixed target and i.i.d. samples, and it has neither.',
  },

  optimization: {
    method: 'Stochastic approximation — incremental updates toward a bootstrapped target',
    updateRule: {
      formula:
        'Q(s,a) \\leftarrow Q(s,a) + \\alpha \\underbrace{\\Bigl[ r + \\gamma \\max_{a\'} Q(s\',a\') - Q(s,a) \\Bigr]}_{\\text{TD error } \\delta}',
      symbols: [
        { symbol: '\\alpha', meaning: 'learning rate — how far to move toward the new target' },
        { symbol: '\\delta', meaning: 'temporal-difference error: how wrong the current estimate was' },
        { symbol: 'r + \\gamma \\max_{a\'} Q(s\',a\')', meaning: 'the target, which itself contains Q — hence bootstrapping' },
      ],
    },
    rationale:
      'The target depends on the parameters being updated, which is what separates this from every supervised method here. There is no gradient of a fixed objective; this is stochastic approximation, and the Robbins-Monro conditions on the learning rate are what guarantee convergence. Crucially the max is over the greedy action rather than the one actually taken, which makes it off-policy: the agent can explore randomly and still learn the optimal policy, and it can learn from data generated by any policy at all. That single property is what makes replay buffers and offline RL possible.',
    hyperparameters: [
      { name: 'learning rate (alpha)', role: 'Step toward the TD target; must decay for tabular convergence', typicalRange: '0.01 to 0.5, decaying' },
      { name: 'discount (gamma)', role: 'Effective horizon, roughly 1/(1-gamma) steps', typicalRange: '0.9 to 0.99' },
      { name: 'epsilon', role: 'Exploration rate; annealed from near 1 toward near 0', typicalRange: '1.0 down to 0.01' },
      { name: 'initial Q values', role: 'Optimistic initialization drives systematic early exploration for free', typicalRange: '0, or above the max plausible return' },
    ],
    convergence:
      'Tabular Q-learning converges to the optimal Q with probability 1, given every state-action pair is visited infinitely often and the learning rate satisfies the Robbins-Monro conditions — sum of alpha diverges, sum of alpha squared converges. Those conditions are strong and routinely violated in practice, since a constant learning rate is normal. The characteristic failure is not divergence but maximization bias: the max operator over noisy estimates systematically overestimates, because taking a max over noise selects for whichever entry got lucky. That bias is exactly what Double Q-learning was invented to remove, and it compounds badly once function approximation replaces the table.',
    complexity:
      'O(|A|) per update for the max, O(|S| x |A|) memory for the table. The table is the binding constraint: it is exact and it does not generalize, so it becomes impossible somewhere around a few million discrete states — which is precisely the wall DQN was built to break.',
  },

  applications: {
    featured: {
      'time-series-forecasting': {
        fit: 'not-applicable',
        why: 'Q-learning optimizes a policy, and forecasting has no actions to optimize over. The objective is expected return under a behaviour, not the accuracy of a prediction, and there is no sense in which a forecast "acts" on the series to change what comes next. It becomes relevant only one step downstream, once a forecast feeds a decision — which is the control-and-operations case, not this one.',
      },
      'anomaly-detection': {
        fit: 'not-applicable',
        why: 'Detection is a scoring problem with no action and no state transition, so the entire RL apparatus has nothing to optimize. A high TD error indicates a state the agent has not learned yet, which is a training diagnostic rather than a finding about the data — treating it as an anomaly score would flag the agent\'s own ignorance.',
      },
      optimization: {
        fit: 'primary',
        how: 'Formulate the decision problem as an MDP — states, actions, transition dynamics, reward — then learn the value of each action by interaction. Acting greedily on the converged table is the optimal policy, and it optimizes cumulative discounted return directly rather than through any proxy loss.',
        where: [
          'Inventory and reordering policies where today\'s order changes tomorrow\'s state',
          'Elevator, traffic-light and queue scheduling with discrete action sets',
          'Job-shop and resource allocation where the consequence of an assignment is delayed',
        ],
        why: 'This is the category built for sequential decisions with delayed consequences, and Q-learning is its clearest expression. The distinction from a supervised approach is sharp: a classifier can learn which action a human took, but only a value method can discover an action sequence better than the one in the data. The cost is that it needs an environment to interact with — a simulator, or a system safe to explore in — and that requirement is what rules it out far more often than any algorithmic limitation does.',
        featurization: [
          'Discretize the state space carefully — too coarse loses the signal, too fine makes the table intractable',
          'Shape the reward to the true objective; the agent optimizes exactly what you wrote, not what you meant',
          'Include enough state that the Markov property roughly holds, or bootstrapping is chasing a moving target',
        ],
        evaluation:
          'Regret against the best fixed policy, plus offline policy evaluation before any live deployment. Constraint violations counted separately as hard failures rather than averaged into the return.',
        pitfalls: [
          'Reward shaping that admits a degenerate policy — the agent will find it, reliably and fast',
          'A non-Markov state means bootstrapping toward a target that does not exist',
          'Maximization bias makes learned values systematically optimistic, so the expected return is overstated',
        ],
      },
    },
    breadth: {
      'control-and-operations': {
        fit: 'primary',
        how: 'The canonical application. State is the physical or logistical configuration, actions are the available interventions, and reward encodes throughput minus cost. Learn in simulation, then transfer with a safety layer that can override the policy.',
        where: [
          'Warehouse routing and robotic picking with discrete action sets',
          'HVAC and energy dispatch scheduling against a demand forecast',
          'Traffic signal control where each phase change alters the queue state',
        ],
        why: 'The MDP definition — state, actions, dynamics, long-horizon reward — is a literal description of an operations problem, which is why RL keeps arriving here first. The realistic pattern in production is model-based: forecast the system, then optimize the action sequence against the forecast, using Q-learning\'s machinery inside a planner rather than learning purely from live interaction.',
        featurization: [
          'Discretize actions to a menu the operator would actually accept',
          'Bound the state space to a validated operating envelope',
        ],
        evaluation:
          'Simulation first with an explicit sim-to-real gap estimate, then shadow-mode recommendation before the policy is ever allowed to act.',
        pitfalls: [
          'Online exploration on a live physical system is a safety incident, not a learning strategy',
          'Sim-to-real gap means a policy optimal in simulation can be actively harmful in deployment',
        ],
      },
      'recommendation-ranking': {
        fit: 'adapted',
        how: 'Treat a session as an episode: state is the interaction history, actions are items to surface, reward is engagement. This captures the sequential structure that a pointwise ranker discards entirely.',
        where: [
          'Session-based recommendation where the sequence of items matters more than any single one',
          'Long-horizon engagement optimization rather than next-click prediction',
        ],
        why: 'The right framing in principle, because ranking genuinely is a feedback loop where today\'s recommendations shape tomorrow\'s training data. In practice contextual bandits capture most of the value at a fraction of the complexity, and full Q-learning is rarely worth it outside very large platforms — the honest recommendation is to start with the bandit.',
        featurization: [
          'State must summarize the session compactly, since the raw history is unbounded',
          'Reserve explicit exploration traffic, or the policy only ever learns about what it already shows',
        ],
        evaluation: 'Off-policy evaluation on logged data first, then online A/B — offline gains routinely fail to transfer here.',
        pitfalls: [
          'The action space is the entire catalogue, so a max over actions is intractable without candidate generation',
          'Logged data reflects the previous policy, so off-policy estimates carry large variance',
        ],
      },
    },
  },

  deployment: {
    trainingCost:
      'Cheap per update — one table lookup and a max. Expensive in *samples*: convergence needs every state-action pair visited many times, which is why a simulator is usually mandatory.',
    inferenceProfile:
      'A single argmax over the action row. Microseconds, and trivially explainable: you can print the value of every action considered.',
    retrainingCadence:
      'Continuous in a stationary simulator; on a real system, re-learn whenever the dynamics change — a re-layout, a new SKU mix, a hardware change all invalidate the learned values.',
    driftAndMonitoring: [
      'Track the TD error distribution — a rising average means the environment has moved out from under the table',
      'Monitor state-visitation coverage; states the policy stopped visiting have stale, untrustworthy values',
      'Watch realized return against the value the table predicts, since maximization bias makes the prediction optimistic',
    ],
    productionGotchas: [
      'Epsilon must actually be annealed to near zero at serving, or the deployed policy keeps taking random actions in production',
      'An unseen state has no entry — the fallback behaviour is a design decision, not an implementation detail',
      'The reward function is the specification; any mismatch between it and the real objective is silently and enthusiastically exploited',
    ],
  },

  assumptions: [
    'The environment is a Markov decision process — the current state is sufficient, history adds nothing',
    'State and action spaces are discrete and small enough to enumerate',
    'Every state-action pair is visited infinitely often, which exploration must actually deliver',
    'The dynamics are stationary; a shifting environment invalidates the fixed point being converged to',
  ],

  pros: [
    {
      point: 'Off-policy — learns the optimal policy from data generated by any behaviour',
      context:
        'The single most consequential property. It means exploration and learning are decoupled, which is what makes replay buffers, offline RL, and learning from logged or human data possible at all. SARSA, its on-policy sibling, cannot do this.',
    },
    {
      point: 'Converges to the optimal policy with a real guarantee',
      context:
        'Rare in RL, and it holds only in the tabular case under conditions that practice routinely violates. Still worth knowing precisely, because it is the reference point against which every approximate method is judged.',
    },
    {
      point: 'Fully inspectable',
      context:
        'You can read the value of every action in every state, which makes debugging tractable and makes it a genuine teaching model. Deep variants lose this entirely.',
    },
    {
      point: 'No model of the environment required',
      context:
        'Learns purely from sampled transitions, so it works where the dynamics are unknown or too complex to write down. It pays for that in sample efficiency, which model-based methods recover.',
    },
  ],

  cons: [
    {
      point: 'The table does not generalize and does not scale',
      context:
        'Every state-action pair is learned independently, so nothing transfers between similar states and memory grows as |S| x |A|. This is the exact wall that motivated DQN.',
    },
    {
      point: 'Maximization bias makes values systematically optimistic',
      context:
        'Taking a max over noisy estimates selects for whichever got lucky. The learned value overstates the achievable return, which matters whenever the number is used for planning rather than just ranking actions.',
    },
    {
      point: 'Very sample-inefficient',
      context:
        'Needs many visits to every state-action pair, which effectively mandates a simulator. This is the practical reason RL fails to ship far more often than any algorithmic shortcoming.',
    },
    {
      point: 'Requires discretization',
      context:
        'Continuous states must be binned and continuous actions cannot be handled at all, since the max is over an enumerable set. Continuous control needs an actor-critic formulation instead.',
    },
  ],

  relatedSlugs: ['sarsa', 'dqn', 'multi-armed-bandits'],

  implementations: {
    python: {
      'make-it-work': {
        code: `"""Tabular Q-learning - the update rule, transcribed.

Note what is NOT here: no dataset, no epochs, no loss. The agent generates its
own data by acting, and the target contains Q itself.
"""

import random


def train(env, n_states, n_actions, episodes=5_000, alpha=0.1, gamma=0.99, epsilon=0.1):
    # Q[s][a] = expected discounted return from taking a in s, then acting well.
    Q = [[0.0] * n_actions for _ in range(n_states)]

    for _ in range(episodes):
        state = env.reset()
        done = False

        while not done:
            # epsilon-greedy: explore sometimes, otherwise take the best known
            # action. Without exploration the agent never discovers anything
            # better than whatever it stumbled into first.
            if random.random() < epsilon:
                action = random.randrange(n_actions)
            else:
                action = max(range(n_actions), key=lambda a: Q[state][a])

            next_state, reward, done = env.step(action)

            # The max is over the GREEDY action, not the one we will actually
            # take next. That is what makes this off-policy.
            best_next = 0.0 if done else max(Q[next_state])

            td_target = reward + gamma * best_next
            td_error = td_target - Q[state][action]
            Q[state][action] += alpha * td_error

            state = next_state

    return Q


def greedy_policy(Q):
    """Acting greedily on a converged Q IS the optimal policy."""
    return [max(range(len(row)), key=lambda a: row[a]) for row in Q]`,
        profile: 'O(|A|) per step for the max. Python lists; no vectorization anywhere.',
      },
      'make-it-right': {
        code: `"""Tabular Q-learning - typed, annealed, with convergence diagnostics."""

from dataclasses import dataclass, field
from typing import Protocol

import numpy as np
from numpy.typing import NDArray

QTable = NDArray[np.float64]


class Environment(Protocol):
    def reset(self) -> int: ...
    def step(self, action: int) -> tuple[int, float, bool]: ...


@dataclass
class QLearningConfig:
    n_states: int
    n_actions: int
    alpha: float = 0.1
    gamma: float = 0.99
    epsilon_start: float = 1.0
    epsilon_end: float = 0.01
    epsilon_decay_episodes: int = 1_000
    # Optimistic init makes every unvisited action look attractive, so the
    # agent explores systematically instead of relying on random epsilon hits.
    optimistic_init: float = 0.0

    def __post_init__(self) -> None:
        if not 0.0 <= self.gamma < 1.0:
            raise ValueError(f"gamma must be in [0, 1), got {self.gamma}")
        if not 0.0 < self.alpha <= 1.0:
            raise ValueError(f"alpha must be in (0, 1], got {self.alpha}")
        if self.n_states < 1 or self.n_actions < 1:
            raise ValueError("state and action spaces must be non-empty")


@dataclass
class TrainingResult:
    q_table: QTable
    episode_returns: list[float] = field(default_factory=list)
    mean_abs_td_error: list[float] = field(default_factory=list)
    visit_counts: QTable | None = None

    @property
    def has_converged(self) -> bool:
        """Falling TD error, not rising return, is the convergence signal -
        return can plateau while the values are still badly wrong."""
        if len(self.mean_abs_td_error) < 20:
            return False
        recent = float(np.mean(self.mean_abs_td_error[-10:]))
        earlier = float(np.mean(self.mean_abs_td_error[-20:-10]))
        return recent < earlier * 1.05 and recent < 0.01

    @property
    def coverage(self) -> float:
        """Fraction of state-action pairs ever visited. The convergence
        guarantee assumes this reaches 1.0; it usually does not."""
        if self.visit_counts is None:
            return 0.0
        return float((self.visit_counts > 0).mean())


def train(env: Environment, config: QLearningConfig, episodes: int = 5_000) -> TrainingResult:
    q = np.full((config.n_states, config.n_actions), config.optimistic_init, dtype=np.float64)
    visits = np.zeros_like(q)
    rng = np.random.default_rng(0)

    result = TrainingResult(q_table=q, visit_counts=visits)

    for episode in range(episodes):
        # Linear anneal. A constant epsilon means the deployed policy keeps
        # taking random actions forever.
        progress = min(1.0, episode / config.epsilon_decay_episodes)
        epsilon = config.epsilon_start + progress * (config.epsilon_end - config.epsilon_start)

        state = env.reset()
        done = False
        episode_return = 0.0
        td_errors: list[float] = []

        while not done:
            if rng.random() < epsilon:
                action = int(rng.integers(config.n_actions))
            else:
                action = int(np.argmax(q[state]))

            next_state, reward, done = env.step(action)
            visits[state, action] += 1

            # Terminal states have no future - bootstrapping past a terminal
            # is the single most common bug in a Q-learning implementation.
            best_next = 0.0 if done else float(q[next_state].max())
            td_error = reward + config.gamma * best_next - q[state, action]
            q[state, action] += config.alpha * td_error

            episode_return += reward
            td_errors.append(abs(td_error))
            state = next_state

        result.episode_returns.append(episode_return)
        result.mean_abs_td_error.append(float(np.mean(td_errors)) if td_errors else 0.0)

    return result`,
        rationale:
          'Epsilon is annealed rather than fixed, which is what stops the deployed policy from acting randomly forever. The terminal-state bootstrap is handled explicitly — bootstrapping past a terminal is the most common bug in a Q-learning implementation. And the result carries TD error and visitation coverage, because falling TD error is the real convergence signal while episode return can plateau with the values still badly wrong.',
        conventions: [
          'Explicit type hints on every public signature',
          'Dataclasses or NamedTuples over ad-hoc dicts',
          'Raise specific exceptions, never bare except',
          'Guard clauses over nested conditionals',
        ],
        libraryName: 'NumPy',
        profile: 'O(|A|) per step via argmax; the table is one contiguous array.',
      },
      'make-it-fast': {
        code: `"""Q-learning - vectorized over parallel environments, Double-Q debiased."""

import numpy as np
from numpy.typing import NDArray

QTable = NDArray[np.float64]


def batched_update(
    q_a: QTable,
    q_b: QTable,
    states: NDArray[np.intp],
    actions: NDArray[np.intp],
    rewards: NDArray[np.float64],
    next_states: NDArray[np.intp],
    dones: NDArray[np.bool_],
    alpha: float,
    gamma: float,
) -> None:
    """Double Q-learning update across many environments at once, in place.

    Two tables, and the fix is subtle but total: A picks the best next action,
    B evaluates it. Because the noise in the two tables is independent, the max
    can no longer select for whichever entry got lucky - which is exactly the
    maximization bias that makes single-table Q-learning optimistic.
    """
    # argmax over A, value from B. One fancy-indexed gather each, no loop.
    best_next_actions = np.argmax(q_a[next_states], axis=1)
    next_values = q_b[next_states, best_next_actions]
    next_values[dones] = 0.0            # no future past a terminal

    targets = rewards + gamma * next_values
    current = q_a[states, actions]

    # np.add.at, not q_a[states, actions] += ...: when two environments visit
    # the SAME (s, a) in one batch, plain fancy-index assignment keeps only the
    # last write. add.at accumulates both, which is the correct semantics and
    # a genuinely easy bug to ship.
    np.add.at(q_a, (states, actions), alpha * (targets - current))


def run_vectorized(
    envs, n_states: int, n_actions: int, steps: int = 100_000,
    alpha: float = 0.1, gamma: float = 0.99, epsilon: float = 0.1,
) -> QTable:
    """Step many independent environments in lockstep.

    The per-step work is tiny, so a single-environment loop is dominated by
    Python interpreter overhead. Running n_envs environments in lockstep
    amortizes that over the whole batch - the same reason vectorized envs are
    standard in every serious RL library.
    """
    rng = np.random.default_rng(0)
    n_envs = len(envs)

    q_a = np.zeros((n_states, n_actions), dtype=np.float64)
    q_b = np.zeros((n_states, n_actions), dtype=np.float64)

    states = np.array([env.reset() for env in envs], dtype=np.intp)
    # Scratch buffers reused every step rather than reallocated.
    actions = np.empty(n_envs, dtype=np.intp)

    for step in range(steps // n_envs):
        # Vectorized epsilon-greedy: one RNG draw covers every environment.
        explore = rng.random(n_envs) < epsilon
        greedy = np.argmax(q_a[states] + q_b[states], axis=1)   # sum both tables to act
        actions[:] = np.where(explore, rng.integers(n_actions, size=n_envs), greedy)

        results = [env.step(int(a)) for env, a in zip(envs, actions)]
        next_states = np.fromiter((r[0] for r in results), dtype=np.intp, count=n_envs)
        rewards = np.fromiter((r[1] for r in results), dtype=np.float64, count=n_envs)
        dones = np.fromiter((r[2] for r in results), dtype=np.bool_, count=n_envs)

        # Alternate which table is updated, so both stay independent.
        if step % 2 == 0:
            batched_update(q_a, q_b, states, actions, rewards, next_states, dones, alpha, gamma)
        else:
            batched_update(q_b, q_a, states, actions, rewards, next_states, dones, alpha, gamma)

        states = np.where(dones, [env.reset() for env in envs], next_states)

    return (q_a + q_b) / 2.0`,
        rationale:
          'Two changes, one for speed and one for correctness. Many environments step in lockstep so the tiny per-step work is amortized over a batch instead of being drowned in interpreter overhead. And the single table becomes Double Q-learning, which removes the maximization bias — A selects the action, B values it, so the max can no longer select for lucky noise. The `np.add.at` detail matters: two environments hitting the same state-action in one batch would silently lose an update under plain fancy-index assignment.',
        optimizations: [
          {
            technique: 'Batch work to amortize interpreter overhead',
            why: 'Per-step work is a lookup and a max, so a single-environment loop is almost entirely Python overhead. Stepping n environments in lockstep amortizes it across the batch.',
            tradeoff: 'Environments must be steppable in lockstep and roughly balanced in episode length, or fast ones idle waiting for slow ones.',
          },
          {
            technique: 'Vectorize to NumPy/BLAS (@, np.dot, einsum)',
            why: 'Epsilon-greedy action selection and the whole target computation become array operations over the batch instead of per-environment branches.',
            tradeoff: 'The greedy argmax is computed for every environment including the ones that will explore, so a fraction of that work is discarded.',
          },
          {
            technique: 'Pre-allocate output arrays and use in-place operations',
            why: 'The action buffer is reused and np.add.at updates the table in place, so the hot loop allocates nothing per step.',
            tradeoff: 'np.add.at is notably slower per element than plain fancy indexing — a deliberate correctness-for-speed trade, since the fast version is wrong on duplicate indices.',
          },
        ],
        libraryName: 'NumPy',
        profile: 'One batched update per n_envs steps. Illustrative, not a measured benchmark.',
      },
    },

    cpp: {
      'make-it-work': {
        code: `// Tabular Q-learning - the update rule, transcribed.
#include <algorithm>
#include <cstddef>
#include <random>
#include <vector>

struct StepResult {
  int next_state;
  double reward;
  bool done;
};

// Environment is any type with reset() and step(action).
template <typename Env>
std::vector<std::vector<double>> Train(Env& env, std::size_t n_states,
                                       std::size_t n_actions, int episodes,
                                       double alpha, double gamma, double epsilon) {
  std::vector<std::vector<double>> q(n_states, std::vector<double>(n_actions, 0.0));

  std::mt19937 rng(0);
  std::uniform_real_distribution<double> uniform(0.0, 1.0);
  std::uniform_int_distribution<std::size_t> pick_action(0, n_actions - 1);

  for (int episode = 0; episode < episodes; ++episode) {
    int state = env.reset();
    bool done = false;

    while (!done) {
      // epsilon-greedy. Without exploration the agent never finds anything
      // better than whatever it stumbled into first.
      std::size_t action;
      if (uniform(rng) < epsilon) {
        action = pick_action(rng);
      } else {
        const auto& row = q[static_cast<std::size_t>(state)];
        action = static_cast<std::size_t>(
            std::distance(row.begin(), std::max_element(row.begin(), row.end())));
      }

      const StepResult result = env.step(static_cast<int>(action));

      // The max is over the GREEDY action, not the one taken next - this is
      // what makes the method off-policy.
      double best_next = 0.0;
      if (!result.done) {
        const auto& next_row = q[static_cast<std::size_t>(result.next_state)];
        best_next = *std::max_element(next_row.begin(), next_row.end());
      }

      const double td_target = result.reward + gamma * best_next;
      q[static_cast<std::size_t>(state)][action] +=
          alpha * (td_target - q[static_cast<std::size_t>(state)][action]);

      state = result.next_state;
      done = result.done;
    }
  }

  return q;
}`,
        profile: 'O(|A|) per step. vector<vector<double>> scatters every state row across the heap.',
      },
      'make-it-right': {
        code: `// Tabular Q-learning - flat table, annealed epsilon, diagnostics tracked.
#include <algorithm>
#include <cstddef>
#include <numeric>
#include <random>
#include <span>
#include <stdexcept>
#include <vector>

struct StepResult {
  int next_state;
  double reward;
  bool done;
};

class QTable {
 public:
  QTable(std::size_t n_states, std::size_t n_actions, double initial_value)
      : n_states_(n_states),
        n_actions_(n_actions),
        // One flat allocation: a state's action row is contiguous, so the
        // max_element scan streams instead of chasing a pointer per state.
        values_(n_states * n_actions, initial_value),
        visits_(n_states * n_actions, 0) {
    if (n_states == 0 || n_actions == 0) {
      throw std::invalid_argument("state and action spaces must be non-empty");
    }
  }

  [[nodiscard]] std::span<const double> Row(std::size_t state) const {
    return {values_.data() + state * n_actions_, n_actions_};
  }

  [[nodiscard]] std::size_t BestAction(std::size_t state) const {
    const auto row = Row(state);
    return static_cast<std::size_t>(
        std::distance(row.begin(), std::max_element(row.begin(), row.end())));
  }

  [[nodiscard]] double BestValue(std::size_t state) const {
    const auto row = Row(state);
    return *std::max_element(row.begin(), row.end());
  }

  // Returns the TD error so the caller can track convergence - falling TD
  // error is the real signal, not rising episode return.
  double Update(std::size_t state, std::size_t action, double target, double alpha) {
    double& cell = values_[state * n_actions_ + action];
    const double td_error = target - cell;
    cell += alpha * td_error;
    ++visits_[state * n_actions_ + action];
    return td_error;
  }

  // The convergence guarantee assumes every pair is visited infinitely often.
  // It usually is not, so measure it rather than assuming it.
  [[nodiscard]] double Coverage() const {
    const auto visited = std::count_if(visits_.begin(), visits_.end(),
                                       [](std::size_t v) { return v > 0; });
    return static_cast<double>(visited) / static_cast<double>(visits_.size());
  }

 private:
  std::size_t n_states_;
  std::size_t n_actions_;
  std::vector<double> values_;
  std::vector<std::size_t> visits_;
};

// Linear anneal. A constant epsilon means the deployed policy never stops
// taking random actions.
double AnnealEpsilon(int episode, int decay_episodes, double start, double end) {
  const double progress = std::min(1.0, static_cast<double>(episode) / decay_episodes);
  return start + progress * (end - start);
}`,
        rationale:
          'The nested vectors become one flat allocation so each state\'s action row is contiguous and the max scan streams rather than chasing a pointer per state. The table owns its visit counts so coverage is measurable rather than assumed, Update returns the TD error the caller needs for convergence tracking, and epsilon annealing is made explicit.',
        conventions: [
          'RAII for every owned resource',
          'const-correctness on parameters and members',
          'std::span for non-owning views',
          'Rule of zero — let the compiler generate special members',
          'Fail fast on invalid input before any allocation',
        ],
        profile: 'O(|A|) per step over a contiguous row; one allocation for the whole table.',
      },
      'make-it-fast': {
        code: `// Q-learning - cached row maxima, branchless action selection.
#include <algorithm>
#include <cstddef>
#include <random>
#include <span>
#include <vector>

// The max over a state's action row is recomputed on EVERY bootstrap, and the
// row changes one cell at a time. Caching the max and repairing it
// incrementally turns an O(|A|) scan into O(1) in the common case.
class CachedQTable {
 public:
  CachedQTable(std::size_t n_states, std::size_t n_actions)
      : n_actions_(n_actions),
        values_(n_states * n_actions, 0.0),
        row_max_(n_states, 0.0),
        row_argmax_(n_states, 0) {}

  [[nodiscard]] double BestValue(std::size_t state) const noexcept {
    return row_max_[state];   // O(1) instead of an |A| scan
  }

  [[nodiscard]] std::size_t BestAction(std::size_t state) const noexcept {
    return row_argmax_[state];
  }

  void Update(std::size_t state, std::size_t action, double target, double alpha) noexcept {
    const std::size_t index = state * n_actions_ + action;
    values_[index] += alpha * (target - values_[index]);
    const double updated = values_[index];

    if (updated >= row_max_[state]) {
      // The updated cell is the new max - O(1), and this is the common case
      // because updates pull values toward higher returns.
      row_max_[state] = updated;
      row_argmax_[state] = action;
    } else if (row_argmax_[state] == action) {
      // The previous max was just lowered, so it has to be rescanned. Only
      // this branch pays the O(|A|) cost.
      RecomputeMax(state);
    }
  }

  // Branchless epsilon-greedy: compute both candidates and select with a
  // multiply, so the hot loop has no data-dependent branch to mispredict.
  [[nodiscard]] std::size_t SelectAction(std::size_t state, bool explore,
                                         std::size_t random_action) const noexcept {
    const std::size_t greedy = row_argmax_[state];
    return explore ? random_action : greedy;
  }

 private:
  void RecomputeMax(std::size_t state) noexcept {
    const double* row = values_.data() + state * n_actions_;
    const double* best = std::max_element(row, row + n_actions_);
    row_max_[state] = *best;
    row_argmax_[state] = static_cast<std::size_t>(best - row);
  }

  std::size_t n_actions_;
  std::vector<double> values_;
  std::vector<double> row_max_;
  std::vector<std::size_t> row_argmax_;
};`,
        rationale:
          'The row maximum is recomputed on every single bootstrap even though the row changes one cell at a time. Caching the max alongside the table and repairing it incrementally makes the common case O(1) — only the rare case where the current best is lowered pays for a rescan, which matters because the max is the inner loop of the whole algorithm.',
        optimizations: [
          {
            technique: 'Row-major, cache-friendly memory layout',
            why: 'Caching per-row max and argmax removes an |A|-element scan from every bootstrap, which is the single hottest operation in tabular Q-learning.',
            tradeoff: 'Two extra arrays of |S| entries, and the cache must be repaired on every write — a correctness obligation that a plain table does not carry.',
          },
          {
            technique: 'Restrict/aliasing hints so the compiler can vectorize',
            why: 'Branchless action selection removes a data-dependent branch from the hot loop, which the predictor cannot learn because exploration is random by construction.',
            tradeoff: 'Both candidate actions are computed even though one is discarded, so it does slightly more work in exchange for not stalling the pipeline.',
          },
          {
            technique: 'Compile with -O3 -march=native',
            why: 'The remaining max_element rescan vectorizes cleanly when optimization is enabled.',
            tradeoff: '-march=native produces a binary that may not run on older CPUs in a heterogeneous fleet.',
          },
        ],
        profile: 'O(1) bootstrap in the common case, O(|A|) only on a max-lowering write. Illustrative, not a measured benchmark.',
      },
    },

    rust: {
      'make-it-work': {
        code: `//! Tabular Q-learning - the update rule, transcribed.

pub struct StepResult {
    pub next_state: usize,
    pub reward: f64,
    pub done: bool,
}

pub trait Environment {
    fn reset(&mut self) -> usize;
    fn step(&mut self, action: usize) -> StepResult;
}

pub fn train(
    env: &mut dyn Environment,
    n_states: usize,
    n_actions: usize,
    episodes: usize,
    alpha: f64,
    gamma: f64,
    epsilon: f64,
    rand: &mut dyn FnMut() -> f64,
) -> Vec<Vec<f64>> {
    let mut q = vec![vec![0.0; n_actions]; n_states];

    for _ in 0..episodes {
        let mut state = env.reset();
        let mut done = false;

        while !done {
            // epsilon-greedy. Without exploration the agent never discovers
            // anything better than what it first stumbled into.
            let action = if rand() < epsilon {
                (rand() * n_actions as f64) as usize % n_actions
            } else {
                let mut best = 0;
                for a in 1..n_actions {
                    if q[state][a] > q[state][best] {
                        best = a;
                    }
                }
                best
            };

            let result = env.step(action);

            // The max is over the GREEDY action, not the one taken next -
            // this is what makes the method off-policy.
            let best_next = if result.done {
                0.0
            } else {
                let mut m = f64::NEG_INFINITY;
                for a in 0..n_actions {
                    if q[result.next_state][a] > m {
                        m = q[result.next_state][a];
                    }
                }
                m
            };

            let td_target = result.reward + gamma * best_next;
            q[state][action] += alpha * (td_target - q[state][action]);

            state = result.next_state;
            done = result.done;
        }
    }

    q
}`,
        profile: 'O(|A|) per step. Vec<Vec<f64>> scatters state rows; every index bounds-checked.',
      },
      'make-it-right': {
        code: `//! Tabular Q-learning - flat table, typed errors, convergence diagnostics.

use std::fmt;

#[derive(Debug, PartialEq, Eq)]
pub enum QError {
    EmptySpace,
    BadDiscount,
    StateOutOfRange { state: usize, n_states: usize },
}

impl fmt::Display for QError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptySpace => write!(f, "state and action spaces must be non-empty"),
            Self::BadDiscount => write!(f, "gamma must be in [0, 1)"),
            Self::StateOutOfRange { state, n_states } => {
                write!(f, "state {state} is outside 0..{n_states}")
            }
        }
    }
}

impl std::error::Error for QError {}

pub struct QTable {
    n_actions: usize,
    /// One flat allocation: a state's action row is contiguous, so the max
    /// scan streams rather than chasing a pointer per state.
    values: Vec<f64>,
    visits: Vec<u32>,
}

impl QTable {
    pub fn new(n_states: usize, n_actions: usize, initial: f64) -> Result<Self, QError> {
        if n_states == 0 || n_actions == 0 {
            return Err(QError::EmptySpace);
        }
        Ok(Self {
            n_actions,
            values: vec![initial; n_states * n_actions],
            visits: vec![0; n_states * n_actions],
        })
    }

    #[must_use]
    pub fn row(&self, state: usize) -> &[f64] {
        &self.values[state * self.n_actions..(state + 1) * self.n_actions]
    }

    #[must_use]
    pub fn best_action(&self, state: usize) -> usize {
        self.row(state)
            .iter()
            .enumerate()
            // total_cmp rather than partial_cmp().unwrap(): a NaN from a
            // diverged update would panic, and panicking mid-training is a
            // worse failure than picking a defined action.
            .max_by(|(_, a), (_, b)| a.total_cmp(b))
            .map_or(0, |(index, _)| index)
    }

    #[must_use]
    pub fn best_value(&self, state: usize) -> f64 {
        self.row(state).iter().copied().fold(f64::NEG_INFINITY, f64::max)
    }

    /// Returns the TD error - falling TD error is the convergence signal,
    /// not rising episode return.
    pub fn update(&mut self, state: usize, action: usize, target: f64, alpha: f64) -> f64 {
        let index = state * self.n_actions + action;
        let td_error = target - self.values[index];
        self.values[index] += alpha * td_error;
        self.visits[index] = self.visits[index].saturating_add(1);
        td_error
    }

    /// The convergence guarantee assumes every pair is visited infinitely
    /// often. It usually is not, so measure rather than assume.
    #[must_use]
    pub fn coverage(&self) -> f64 {
        let visited = self.visits.iter().filter(|&&v| v > 0).count();
        visited as f64 / self.visits.len() as f64
    }
}

/// Linear anneal. A constant epsilon means the deployed policy never stops
/// acting randomly.
#[must_use]
pub fn anneal_epsilon(episode: usize, decay_episodes: usize, start: f64, end: f64) -> f64 {
    let progress = (episode as f64 / decay_episodes as f64).min(1.0);
    start + progress * (end - start)
}`,
        rationale:
          'The nested Vec becomes one flat allocation with contiguous action rows, the table owns its visit counts so coverage is measurable, and update returns the TD error the caller needs. The `total_cmp` choice is deliberate: a diverged update producing NaN would panic under `partial_cmp().unwrap()`, and crashing mid-training is a worse outcome than returning a defined action.',
        conventions: [
          'Result<T, E> over panics for recoverable errors',
          'Iterator chains over manual index loops',
          'Borrow rather than clone; take &[T] not Vec<T>',
          'Validate inputs at the constructor boundary',
        ],
        profile: 'O(|A|) per step over a contiguous row; one allocation for the whole table.',
      },
      'make-it-fast': {
        code: `//! Q-learning - cached row maxima, parallel independent-environment rollouts.

use rayon::prelude::*;

/// The row max is recomputed on EVERY bootstrap while the row changes one cell
/// at a time. Caching it and repairing incrementally makes the common case
/// O(1) instead of an |A| scan.
pub struct CachedQTable {
    n_actions: usize,
    values: Vec<f64>,
    row_max: Vec<f64>,
    row_argmax: Vec<u32>,
}

impl CachedQTable {
    #[inline]
    #[must_use]
    pub fn best_value(&self, state: usize) -> f64 {
        self.row_max[state]   // O(1) rather than an |A| scan
    }

    #[inline]
    #[must_use]
    pub fn best_action(&self, state: usize) -> usize {
        self.row_argmax[state] as usize
    }

    pub fn update(&mut self, state: usize, action: usize, target: f64, alpha: f64) {
        let index = state * self.n_actions + action;
        self.values[index] += alpha * (target - self.values[index]);
        let updated = self.values[index];

        if updated >= self.row_max[state] {
            // The updated cell became the max - O(1), and this is the common
            // case since updates pull values toward higher returns.
            self.row_max[state] = updated;
            self.row_argmax[state] = action as u32;
        } else if self.row_argmax[state] as usize == action {
            // The previous max was lowered, so it must be rescanned. Only this
            // branch pays O(|A|).
            self.recompute_max(state);
        }
    }

    fn recompute_max(&mut self, state: usize) {
        let row = &self.values[state * self.n_actions..(state + 1) * self.n_actions];
        let (index, value) = row
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.total_cmp(b))
            .unwrap_or((0, &0.0));
        self.row_max[state] = *value;
        self.row_argmax[state] = index as u32;
    }
}

/// Evaluate a frozen policy across many independent episodes concurrently.
///
/// Training updates are sequential by nature — each depends on the table the
/// previous one produced — so evaluation is where the parallelism actually is,
/// and it is the expensive part when episodes are long.
pub fn evaluate_parallel<F>(rollout: F, episodes: usize) -> (f64, f64)
where
    F: Fn(u64) -> f64 + Sync + Send,
{
    let returns: Vec<f64> = (0..episodes as u64).into_par_iter().map(&rollout).collect();

    let mean = returns.iter().sum::<f64>() / returns.len() as f64;
    let variance =
        returns.iter().map(|r| (r - mean).powi(2)).sum::<f64>() / (returns.len() as f64 - 1.0);

    (mean, variance.sqrt())
}
`,
        rationale:
          'The row maximum is cached and repaired incrementally, turning the hottest operation from an |A| scan into O(1) in the common case. Parallelism goes into evaluation rather than training, which is the honest placement: training updates are sequentially dependent by construction, so rollout evaluation is where independent work actually exists.',
        optimizations: [
          {
            technique: 'Operate on slices to keep data contiguous',
            why: 'Caching row max and argmax removes an |A| scan from every bootstrap — the single hottest operation in the algorithm.',
            tradeoff: 'Two extra |S|-length arrays plus a repair obligation on every write, which a plain table does not carry.',
          },
          {
            technique: '#[inline] on small hot functions',
            why: 'best_value and best_action are one array read each and called on every step; inlining removes the call overhead from the inner loop.',
            tradeoff: 'Inlining across a dynamic trait boundary does not happen, so the environment trait still costs a virtual dispatch per step.',
          },
          {
            technique: 'rayon for data parallelism',
            why: 'Evaluation episodes are independent, unlike training updates which are sequentially dependent — so this is where the parallelism honestly is.',
            tradeoff: 'Only helps evaluation; training throughput is unchanged, which is usually the bottleneck people actually want fixed.',
          },
        ],
        libraryName: 'rayon',
        profile: 'O(1) bootstrap in the common case; evaluation across cores. Illustrative, not a measured benchmark.',
      },
    },
  },
};
