/**
 * ai-ml-engineering glossary terms.
 *
 * Ledger populated in Phase 1 (slug/term/category/voiceTemplate only).
 * `definition` fields are filled in Phase 2 by an isolated content subagent
 * — see plan §7. Source lineage: scratchpad/glossary-sources/{model,
 * system_design_MLE,general}.txt (LLM-application-layer slice) plus
 * src/data/AiSystemInformation.ts and src/docs/Thomas_To_Resume.md — this
 * category covers how models are put into products, as distinct from
 * data-science-ml's "how models are built."
 *
 * Phase 3 revision: the first draft of every definition in this file opened
 * with a literal "[Term] is a mechanism/structure/constraint that…" —
 * leaking the internal voiceTemplate label into the prose instead of using
 * a natural domain noun the way the encoder/decoder anchor does ("a
 * function that…"). Reworded below to drop that template leakage; technical
 * content is unchanged.
 */

import type { GlossaryTerm } from './types';

export const GLOSSARY_TERMS_AI_ML_ENGINEERING: GlossaryTerm[] = [
  { slug: 'retrieval-augmented-generation', term: 'Retrieval-Augmented Generation (RAG)', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Retrieval-augmented generation, at query time, retrieves relevant passages from an external corpus via a search step and injects them into the model's input context, so generation is conditioned on retrieved text rather than solely on knowledge encoded in the model's trained parameters.", relatedSlugs: ['vector-database', 'embedding-model'] },
  { slug: 'agentic-rag', term: 'Agentic RAG', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Agentic RAG wraps retrieval inside an agent's reasoning loop, letting the system decide whether to retrieve, how to reformulate the query, or whether to retrieve again based on an evaluation of what came back, rather than always executing a single fixed retrieve-then-generate pass.", relatedSlugs: ['retrieval-augmented-generation', 'agentic-workflow'] },
  { slug: 'cache-augmented-generation', term: 'Cache-Augmented Generation (CAG)', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Cache-augmented generation preloads a fixed body of context into the model's key-value cache ahead of time, so a query is answered against that precomputed state directly instead of running a retrieval step at request time. This trades the ability to reflect newly changed source content for lower per-query latency, since the cache must be rebuilt whenever the underlying context changes.", relatedSlugs: ['retrieval-augmented-generation'] },
  { slug: 'embedding-model', term: 'Embedding Model', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: 'An embedding model is a function that transforms a discrete input — text, an image, code — into a fixed-length dense vector positioned in a continuous space, such that inputs with similar meaning are mapped to vectors that sit close together.', relatedSlugs: ['encoder', 'cosine-similarity'] },
  { slug: 'vector-database', term: 'Vector Database', category: 'ai-ml-engineering', voiceTemplate: 'structure', definition: 'A vector database indexes high-dimensional embedding vectors alongside their source metadata, organizing them so an approximate-nearest-neighbor search can return the closest vectors to a query without scanning every stored vector.', relatedSlugs: ['embedding-model', 'cosine-similarity'] },
  { slug: 'cosine-similarity', term: 'Cosine Similarity', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Cosine similarity takes two vectors as input and computes the cosine of the angle between them, producing a score between -1 and 1 that measures directional alignment independent of each vector's magnitude." },
  { slug: 'prompt-engineering', term: 'Prompt Engineering', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Prompt engineering transforms a task's intent into structured input text — instructions, constraints, and examples — that shapes the distribution of outputs a model samples from, without altering the model's underlying weights." },
  { slug: 'fine-tuning', term: 'Fine-Tuning', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Fine-tuning takes a pretrained model's existing weights as a starting point and continues training them on a smaller, task-specific dataset, updating the parameters themselves so the model's behavior shifts rather than only its input." },
  { slug: 'lora', term: 'LoRA (Low-Rank Adaptation)', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "LoRA freezes a pretrained model's original weight matrices and instead trains a pair of much smaller low-rank matrices injected alongside them, so adaptation happens through a small added set of parameters rather than updating the full weight matrix directly.", relatedSlugs: ['fine-tuning'] },
  { slug: 'guardrails', term: 'Guardrails', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Guardrails intercept a model's input or output and check it against a defined policy — a content filter, schema, or safety rule — blocking, rewriting, or flagging anything that fails the check before it reaches the user or a downstream system." },
  { slug: 'function-calling', term: 'Function Calling', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: 'Function calling has a model, given a set of available function schemas, output a structured call — a function name and its arguments — instead of free-form text, so the calling application can parse and execute that call directly rather than interpreting prose.' },
  { slug: 'agentic-workflow', term: 'Agentic Workflow', category: 'ai-ml-engineering', voiceTemplate: 'structure', definition: 'An agentic workflow arranges a task into a bounded loop of reasoning, tool-calling, and observation steps rather than a single input-to-output pass, with an explicit stopping condition governing how many iterations the loop is allowed to take.', relatedSlugs: ['function-calling', 'tool-use-validation'] },
  { slug: 'tool-use-validation', term: 'Tool-Use Validation', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Tool-use validation checks a tool's returned output against an expected schema or type before that output is fed back into an agent's reasoning loop, so a malformed or unexpected result is caught and handled rather than silently corrupting the next reasoning step." },
  { slug: 'prompt-injection', term: 'Prompt Injection', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Prompt injection happens when untrusted content — user input or retrieved text — carries instructions that the model interprets with the same authority as its system prompt, letting that content override intended behavior when system instructions and external content aren't kept in structurally separate channels.", relatedSlugs: ['guardrails'] },
  { slug: 'hybrid-retrieval', term: 'Hybrid Retrieval', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: 'Hybrid retrieval runs a dense vector search and a sparse keyword search over the same corpus and merges or reranks their results, combining semantic matching with exact-term matching rather than relying on either search alone.', relatedSlugs: ['retrieval-augmented-generation'] },
  { slug: 'recall-at-k', term: 'Recall@k', category: 'ai-ml-engineering', voiceTemplate: 'constraint', definition: 'Recall@k measures what fraction of all truly relevant documents for a query appear within the top-k results a retrieval system returns, bounding how large k must be set before an acceptable share of relevant material is actually reachable by the generation step downstream.' },
  { slug: 'model-context-protocol', term: 'Model Context Protocol (MCP)', category: 'ai-ml-engineering', voiceTemplate: 'structure', definition: 'Model Context Protocol defines a standardized interface between an LLM application and external tools or data sources, so a client and a server can exchange capabilities and context through one shared protocol instead of each integration requiring its own bespoke connector.' },
  { slug: 'agent-orchestration', term: 'Agent Orchestration', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: 'Agent orchestration takes a task and a set of available agents or subagents as input and routes, sequences, or delegates subtasks among them, so a controller — not any single agent — determines who acts next and how partial results are combined into a final output.' },
  { slug: 'vision-language-model', term: 'Vision-Language Model (VLM)', category: 'ai-ml-engineering', voiceTemplate: 'structure', definition: 'A vision-language model joins a vision encoder to a language model through a shared representation space, so image and text inputs are aligned into the same embedding space and can be reasoned about jointly rather than processed by two independent, unconnected pipelines.' },
  { slug: 'edge-inference', term: 'Edge Inference', category: 'ai-ml-engineering', voiceTemplate: 'structure', definition: "Edge inference places a model's inference step on local, on-device hardware close to where data is generated, rather than routing every request to a centralized server, trading available compute for lower latency and reduced dependency on network connectivity." },
  { slug: 'hardware-agnostic-inference', term: 'Hardware-Agnostic Inference', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Hardware-agnostic inference routes a model's computation through an abstraction layer over the underlying device — CPU, GPU, or TPU — so the same model code runs across different hardware backends without being rewritten for each one." },
  { slug: 'streaming-inference', term: 'Streaming Inference', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: "Streaming inference emits a model's output incrementally, token by token, as each one is generated, rather than withholding the response until the full generation is complete, so a client can begin rendering output before the full sequence exists." },
  { slug: 'deterministic-seeding', term: 'Deterministic Seeding', category: 'ai-ml-engineering', voiceTemplate: 'mechanism', definition: 'Deterministic seeding fixes a random number generator\'s seed value before a stochastic process — such as token sampling or weight initialization — runs, so the same inputs and seed reproduce the same output instead of varying from run to run.' },
];
