/**
 * data-engineering glossary terms.
 *
 * Ledger populated in Phase 1 (slug/term/category/voiceTemplate only).
 * `definition` fields are filled in Phase 2 by an isolated content subagent
 * — see plan §7. Source lineage: scratchpad/glossary-sources/data.txt,
 * extracted from public/excalidraw/data.excalidraw @ 04b1d4e649058ecea338cc0d50e91b66adb4fa5d.
 */

import type { GlossaryTerm } from './types';

export const GLOSSARY_TERMS_DATA_ENGINEERING: GlossaryTerm[] = [
  { slug: 'etl-vs-elt', term: 'ETL vs. ELT', category: 'data-engineering', voiceTemplate: 'structure', definition: 'ETL vs. ELT describes where transformation sits relative to loading: ETL transforms data before it lands in the target system, while ELT loads raw data first and transforms it in place using the target system\'s own compute. The two arrangements draw the boundary between "processing layer" and "storage layer" in different places, which changes who owns the transformation logic and how early bad data can be caught.' },
  { slug: 'batch-vs-stream-processing', term: 'Batch vs. Stream Processing', category: 'data-engineering', voiceTemplate: 'structure', definition: 'Batch vs. stream processing is an arrangement of when data gets processed relative to when it arrives: batch processing groups records into scheduled, bounded windows and processes them together, while stream processing treats each record as an unbounded unit processed as it lands. The boundary between the two is a tradeoff between freshness and operational simplicity, not a measure of sophistication — batch is cheaper and easier to debug, streaming buys lower latency at the cost of that simplicity.' },
  { slug: 'idempotent-pipeline-design', term: 'Idempotent Pipeline Design', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'Idempotent pipeline design builds a task so that running it once or many times against the same input leaves the target data in the same end state, using upserts, deterministic partition overwrites, or natural/composite keys instead of blind appends. That property lets a failed or retried run be re-executed safely, without duplicating or corrupting data that a prior attempt already wrote.' },
  { slug: 'delivery-semantics', term: 'Delivery Semantics', category: 'data-engineering', voiceTemplate: 'constraint', definition: 'Delivery semantics is the bound a messaging or processing system guarantees on how many times a given record is delivered to a consumer: at-most-once risks silent loss, at-least-once risks duplicates, and exactly-once eliminates both at the cost of extra coordination. Most systems default to at-least-once delivery paired with idempotent writes, and reserve the overhead of true exactly-once guarantees for cases where a duplicate is unacceptable.' },
  { slug: 'schema-evolution', term: 'Schema Evolution', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'Schema evolution treats the schema shared between a data producer and its consumers as a versioned contract, checked against a schema registry, so that a change is classified as backward-compatible, forward-compatible, or breaking before it ships. A breaking change is rejected at write time and fails loudly, rather than being allowed to silently corrupt every downstream table built on top of it.' },
  { slug: 'data-validation-ingestion', term: 'Data Validation at Ingestion', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'Data validation at ingestion checks incoming data — row counts, null rates, referential integrity, value ranges — against explicit rules before it is committed to a production table. A record or batch that fails a rule is rejected or quarantined at that boundary, so invalid state never propagates downstream into business logic that assumes clean input.' },
  { slug: 'dag-orchestration', term: 'DAG Orchestration', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'DAG orchestration models a pipeline as a directed acyclic graph of small, single-purpose tasks connected by explicit dependencies, then schedules, executes, and retries each task according to that graph. Because the graph is acyclic and each task is independently retryable, a failed task can be rerun on its own without forcing the whole pipeline to restart.' },
  { slug: 'backfill', term: 'Backfill', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'Backfill re-runs a pipeline\'s existing logic against a range of past execution dates or partitions to populate or correct historical output, rather than writing separate one-off code for the historical case. It only works if the pipeline takes the execution date as a parameter instead of hardcoding "today," so the same code path produces a correct result for any point in history.' },
  { slug: 'data-aware-dependency', term: 'Data-Aware Dependency', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'A data-aware dependency triggers a downstream task from the actual availability of an upstream dataset or asset — detected by a sensor or asset check — rather than from a fixed time offset in a schedule. It replaces the assumption that an upstream job is probably finished by a given time with an explicit signal that only fires once the required data actually exists.' },
  { slug: 'star-schema', term: 'Star Schema', category: 'data-engineering', voiceTemplate: 'structure', definition: 'A star schema arranges one central fact table, holding measurable events, around denormalized dimension tables that describe those events\' attributes, with the fact table joined directly to each dimension and no intermediate join levels between them. That flat, one-hop join structure is what keeps queries simple and keeps the schema broadly compatible with BI tooling.' },
  { slug: 'slowly-changing-dimension', term: 'Slowly Changing Dimension (SCD)', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'A slowly changing dimension handles updates to a dimension table\'s attributes over time: Type 1 overwrites the existing row in place and discards the prior value, while Type 2 inserts a new effective-dated row and leaves the old one intact, building a full history of how the attribute changed. Which type applies is a per-column decision about whether the historical value needs to stay queryable.' },
  { slug: 'data-partitioning', term: 'Data Partitioning', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'Data partitioning physically splits a dataset into separate files or subdirectories keyed on a column, typically date, so a query filtering on that column can skip every partition it doesn\'t need instead of scanning the whole dataset. Partition boundaries are chosen to match the columns queries actually filter on, and target a file size range roughly 100MB-1GB, large enough to avoid per-file overhead but small enough to keep skipping effective.' },
  { slug: 'columnar-storage-format', term: 'Columnar Storage Format', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'A columnar storage format lays a dataset\'s values out column by column on disk rather than row by row, so a query reading only a subset of columns can skip the bytes belonging to every other column entirely. Grouping like values together this way also compresses more effectively, which is why analytical workloads that scan and aggregate over many rows but few columns favor it.' },
  { slug: 'denormalization', term: 'Denormalization', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'Denormalization duplicates or pre-joins data that would otherwise live in separate normalized tables, converting join computation that would happen at read time into redundant storage and update work done ahead of time. It trades storage space and write-time complexity for fewer joins per read, which pays off when a table is read far more often than it changes.' },
  { slug: 'data-lake', term: 'Data Lake', category: 'data-engineering', voiceTemplate: 'structure', definition: 'A data lake is a storage arrangement that holds data in its raw, native format — structured, semi-structured, or unstructured — without requiring a schema to be defined at write time. Structure is imposed later, at read time, by whatever process consumes the data, which keeps ingestion permissive at the cost of pushing schema enforcement downstream.' },
  { slug: 'data-warehouse', term: 'Data Warehouse', category: 'data-engineering', voiceTemplate: 'structure', definition: 'A data warehouse is a storage arrangement that holds structured data organized into a fixed, enforced schema — typically fact and dimension tables — defined before data is written, not after. That upfront schema enforcement is what separates it from a data lake, and is what makes the data directly consumable by analytical and BI queries without an additional interpretation step.' },
  { slug: 'data-lakehouse', term: 'Data Lakehouse', category: 'data-engineering', voiceTemplate: 'structure', definition: 'A data lakehouse layers warehouse-style schema enforcement, transactions, and metadata management directly on top of data-lake object storage, collapsing what were previously two separate systems into one. The same underlying files serve both raw storage and schema-enforced analytical querying, removing the separate load step that used to move data from a lake into a warehouse.', relatedSlugs: ['data-lake', 'data-warehouse'] },
  { slug: 'change-data-capture', term: 'Change Data Capture (CDC)', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'Change data capture reads a source database\'s transaction log to detect row-level inserts, updates, and deletes as they happen, and emits each one as a discrete change event. It produces a continuous stream of state changes without repeatedly querying the source table, so downstream systems can replicate or react to changes with minimal added load on the source.' },
  { slug: 'data-lineage', term: 'Data Lineage', category: 'data-engineering', voiceTemplate: 'structure', definition: 'Data lineage is the recorded chain of custody for a piece of data — every upstream source, transformation, and downstream consumer it has passed through — maintained as connected metadata rather than left implicit in pipeline code. That chain is what lets a downstream error be traced back to the specific source or transformation responsible for it, instead of investigated as an isolated incident.' },
  { slug: 'data-mesh', term: 'Data Mesh', category: 'data-engineering', voiceTemplate: 'structure', definition: 'A data mesh assigns ownership of a domain\'s data to the team that produces it, with each domain\'s dataset treated as a self-contained product carrying its own schema, quality contract, and access interface, rather than all data being centralized under one platform team. Ownership boundaries follow the organization\'s domains, not a single shared pipeline, so a change to one domain\'s data does not require coordinating through a central team.' },
  { slug: 'small-files-problem', term: 'Small Files Problem', category: 'data-engineering', voiceTemplate: 'constraint', definition: 'The small files problem is the constraint that appears when a dataset is stored as many files well below a storage system\'s efficient read size, so a query engine spends more time opening files and reading per-file metadata than it spends reading actual content. It bounds how small a partition file can get before that per-file overhead dominates scan time, which is why partitioning strategies target a minimum file size, roughly 100MB-1GB, instead of partitioning as finely as possible.' },
  { slug: 'dead-letter-queue', term: 'Dead-Letter Queue', category: 'data-engineering', voiceTemplate: 'mechanism', definition: 'A dead-letter queue is a destination that a processing system routes a message to after it repeatedly fails to be processed successfully, pulling that poison record out of the primary queue so it can no longer block or endlessly retry the records behind it. The failed message is preserved there for inspection or later reprocessing, rather than being silently dropped or allowed to halt the pipeline.' },
  { slug: 'oltp-vs-olap', term: 'OLTP vs. OLAP', category: 'data-engineering', voiceTemplate: 'structure', definition: 'OLTP vs. OLAP is an arrangement of a database\'s schema and storage layout around one of two opposing access patterns: OLTP schemas are normalized and optimized for many small, concurrent read/write transactions, while OLAP schemas are denormalized, often into star schemas, and optimized for large, read-heavy analytical scans. The two are typically run as separate systems because the indexing and normalization each pattern needs works against the other.' },
];
