/**
 * evaluation-observability glossary terms.
 *
 * Ledger populated in Phase 1 (slug/term/category/voiceTemplate only).
 * `definition` fields are filled in Phase 2 by an isolated content subagent
 * — see plan §7. Source lineage: scratchpad/glossary-sources/{system_design_MLE,
 * ops}.txt plus CLAUDE.md §9 (Logging & Observability). SLI/SLO/SLA/error-budget
 * are defined here (once, per plan §1) even though design.excalidraw's Design
 * frame also mentions them — systems-design references these via relatedSlugs
 * rather than redefining.
 */

import type { GlossaryTerm } from './types';

export const GLOSSARY_TERMS_EVALUATION_OBSERVABILITY: GlossaryTerm[] = [
  { slug: 'sli', term: 'Service Level Indicator (SLI)', category: 'evaluation-observability', voiceTemplate: 'constraint', definition: 'A Service Level Indicator is a directly measured quantity of a system\'s behavior, such as request latency or error rate, sampled from real traffic over a defined window. It is the raw measurement layer that SLOs and SLAs are built on top of — an SLI carries no target or consequence by itself, only a number.', relatedSlugs: ['slo'] },
  { slug: 'slo', term: 'Service Level Objective (SLO)', category: 'evaluation-observability', voiceTemplate: 'constraint', definition: 'A Service Level Objective is a constraint on an SLI, expressed as a target threshold over a rolling window — such as a minimum percentage of requests served within a latency bound — agreed to internally as the reliability bar a team designs and operates against. The error budget itself is fixed by the SLO target alone; the gap between actual performance and that target determines how much of the budget has been spent.', relatedSlugs: ['sli', 'sla', 'error-budget'] },
  { slug: 'sla', term: 'Service Level Agreement (SLA)', category: 'evaluation-observability', voiceTemplate: 'constraint', definition: 'A Service Level Agreement is a constraint on an SLO, escalated from an internal target into an externally binding commitment to a customer, with contractual consequences (credits, penalties) if it is missed. SLAs are typically set looser than the internal SLO they are derived from, so the operating team breaches its own objective before it breaches the customer-facing agreement.', relatedSlugs: ['slo'] },
  { slug: 'error-budget', term: 'Error Budget', category: 'evaluation-observability', voiceTemplate: 'constraint', definition: 'An error budget is a constraint on how much unreliability an SLO permits before corrective action is required — it is 100% minus the SLO target, converted into an allowance of failed requests or downtime over the measurement window. Spending the budget on a risky deploy is acceptable; exhausting it is a forcing function that should freeze further risky changes until reliability recovers.', relatedSlugs: ['slo'] },
  { slug: 'data-drift', term: 'Data Drift', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'Data drift is the umbrella term for any change in the statistical distribution of production data relative to what a model was trained on — inputs, outputs, or both — detected by comparing live traffic against a reference distribution captured at training time. On its own it only says the data looks different now; it does not claim whether the input-output relationship the model learned is still valid, which is what covariate shift and concept drift each pin down more precisely.', relatedSlugs: ['concept-drift', 'covariate-shift'] },
  { slug: 'concept-drift', term: 'Concept Drift', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'Concept drift occurs when the relationship between a model\'s inputs and the correct output changes over time, so an input that once mapped to one label or value now maps to a different one even though the input distribution itself is unchanged. Because the inputs still look statistically normal, concept drift is invisible to input-distribution monitors and only shows up once delayed ground-truth labels arrive.', relatedSlugs: ['data-drift'] },
  { slug: 'covariate-shift', term: 'Covariate Shift', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'Covariate shift is a specific form of data drift in which the distribution of input features changes while the conditional relationship between inputs and outputs stays fixed. It transforms which region of the input space the model is asked to predict on, which can degrade accuracy even without any change to the underlying labeling function.', relatedSlugs: ['data-drift'] },
  { slug: 'degenerate-feedback-loop', term: 'Degenerate Feedback Loop', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'A degenerate feedback loop occurs when a model\'s own predictions influence the future user behavior that becomes its next training data, so the model reinforces its existing biases rather than learning from an independent signal. It is corrected by injecting randomization or exploration into what is served, so the training data reflects outcomes the model did not itself cause.' },
  { slug: 'model-staleness', term: 'Model / Label Staleness', category: 'evaluation-observability', voiceTemplate: 'constraint', definition: 'Model or label staleness is a constraint on how long a model or its training labels remain valid, bounded by how quickly the real-world process they describe changes. A model can be correct at the moment it is trained and still degrade purely from the passage of time, independent of any drift in the input distribution, which is why staleness is tracked and retraining is triggered on elapsed time or data volume rather than on accuracy alone.' },
  { slug: 'monitoring-vs-observability', term: 'Monitoring vs. Observability', category: 'evaluation-observability', voiceTemplate: 'structure', definition: 'Monitoring is the tracking, measurement, and logging of predefined metrics against known failure modes, answering questions decided in advance. Observability is the broader property of a system exposing enough internal state — logs, traces, and metrics correlated together — that an engineer can answer questions about failure modes that were never anticipated; monitoring is one input into observability, not a substitute for it.' },
  { slug: 'golden-dataset', term: 'Golden Dataset', category: 'evaluation-observability', voiceTemplate: 'structure', definition: 'A golden dataset is a fixed, human-vetted set of input-output pairs held apart from production data and treated as ground truth for evaluation. It establishes the reference structure that automated evaluators, including an LLM-as-judge, are checked against so that evaluation quality does not silently drift along with the system it is measuring.', relatedSlugs: ['llm-as-judge'] },
  { slug: 'llm-as-judge', term: 'LLM-as-Judge', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'LLM-as-judge uses a language model to score or compare another model\'s outputs against a rubric, transforming an evaluation task that would otherwise require manual human review into an automated, repeatable judgment. Its reliability depends on periodically validating its scores against a golden dataset, since the judge model carries its own biases and blind spots.', relatedSlugs: ['golden-dataset'] },
  { slug: 'structured-logging', term: 'Structured Logging', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'Structured logging transforms a log event from a free-text string into a consistent set of key-value fields — level, timestamp, correlation ID, sanitized context — so the output can be parsed, filtered, and aggregated by machine rather than read line by line, with any PII or secrets scrubbed before the event is written.', relatedSlugs: ['correlation-id'] },
  { slug: 'correlation-id', term: 'Correlation ID', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'A correlation ID is a unique identifier generated at the start of a request and attached to every log line and downstream call that request produces, transforming a scattered set of independent log entries into a single traceable sequence. Without it propagating through every hop, including async queues, the chain of causality across services cannot be reconstructed after the fact.', relatedSlugs: ['distributed-tracing'] },
  { slug: 'distributed-tracing', term: 'Distributed Tracing', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'Distributed tracing transforms a single logical request into a tree of timed spans, one per service or operation it touches, linked together by a shared trace ID as the request crosses process and network boundaries. This turns an otherwise opaque cross-service call chain into a structure that shows exactly which hop introduced latency or failure.', relatedSlugs: ['correlation-id'] },
  { slug: 'golden-signals', term: 'Golden Signals', category: 'evaluation-observability', voiceTemplate: 'structure', definition: 'The golden signals are four metrics — latency, traffic, errors, and saturation — treated as the minimum structure a service dashboard should default to before adding anything custom. Together they are structured to answer a single question, whether the system is currently on fire, without requiring deeper investigation.' },
  { slug: 'population-stability-index', term: 'Population Stability Index (PSI)', category: 'evaluation-observability', voiceTemplate: 'mechanism', definition: 'The Population Stability Index buckets a feature\'s values and compares the proportion of observations in each bucket between a reference distribution and a current one, transforming that comparison into a single scalar score. A higher PSI value indicates greater divergence between the two distributions, making it a leading proxy signal for data drift that does not require waiting on delayed ground-truth labels.', relatedSlugs: ['data-drift'] },
  { slug: 'blameless-postmortem', term: 'Blameless Postmortem', category: 'evaluation-observability', voiceTemplate: 'structure', definition: 'A blameless postmortem is a structured incident review that attributes an outage to systemic and process gaps rather than to the individual engineer who triggered it, on the premise that any engineer given the same context and tooling would have made the same decision. This structure is what makes root-cause analysis honest: engineers report the full sequence of events accurately only when doing so carries no personal risk.' },
];
