/**
 * gpu-cuda glossary terms.
 *
 * Ledger populated in Phase 1 (slug/term/category/voiceTemplate only).
 * `definition` fields are filled in Phase 2 by an isolated content subagent
 * — see plan §7. Source lineage (Directive #3 — authoritative, not a
 * summary-of-a-summary): scratchpad/glossary-sources/{GPU-TPU,
 * cuda-distributed-computing,cuda-flash-attention}.txt, extracted via
 * scripts/extractBoardText.ts from:
 *   public/excalidraw/GPU-TPU.excalidraw                    @ de728202f26d0176cf416b1fd2e47ce7da9d5c57
 *   public/excalidraw/cuda-distributed-computing.excalidraw @ 9578e0417a3eaf937a58b3fa9dffed6375b14e59
 *   public/excalidraw/cuda-flash-attention.excalidraw       @ 5fc35841185265fdc40ad15da22b97bbc1e98b44
 * plus https://modal.com/gpu-glossary (structural reference).
 */

import type { GlossaryTerm } from './types';

export const GLOSSARY_TERMS_GPU_CUDA: GlossaryTerm[] = [
  { slug: 'streaming-multiprocessor', term: 'Streaming Multiprocessor (SM)', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A streaming multiprocessor is the GPU\'s core processing unit: it takes a batch of thread blocks assigned by the scheduler and executes their instructions across its own CUDA cores, tensor cores, register file, and shared memory, so that many blocks run independently and in parallel across the chip\'s full set of SMs.' },
  { slug: 'cuda-core', term: 'CUDA Core', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A CUDA core is the arithmetic unit inside a streaming multiprocessor that takes one thread\'s scalar instruction — an integer or floating-point operation — and executes it each cycle, so a single SM\'s many CUDA cores retire many threads\' worth of scalar math in parallel.' },
  { slug: 'tensor-core', term: 'Tensor Core', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A tensor core is specialized hardware that takes small matrix tiles as input and produces a fused multiply-accumulate matrix product in a single operation, so it converts what would be many sequential scalar multiply-adds on CUDA cores into one wide operation, raising raw compute throughput for matrix-heavy workloads like attention and MLP layers.' },
  { slug: 'warp', term: 'Warp', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A warp is a fixed-size group of threads (32 on NVIDIA hardware) that the warp scheduler issues a single instruction to at a time, so every thread in the warp executes the same instruction in lockstep on its own data — this grouping is the actual unit of scheduling and execution, one level below the thread block a programmer writes.' },
  { slug: 'thread-block', term: 'Thread Block', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A thread block is a programmer-defined group of threads that is assigned as a whole to a single streaming multiprocessor, so that all its threads can share that SM\'s shared memory and synchronize with each other, while different blocks execute independently and cannot communicate directly.' },
  { slug: 'grid-cuda', term: 'Grid', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A grid is the top level of CUDA\'s thread hierarchy: it takes a kernel launch configuration and organizes the requested thread blocks into it, so the GPU\'s scheduler can distribute those blocks across all available streaming multiprocessors to cover the full problem size.' },
  { slug: 'kernel-cuda', term: 'Kernel', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A kernel is a function marked to run on the device that the host launches with a specified grid and block configuration, so that the same function body executes concurrently across many threads, each computing its own slice of the output from a unique index derived from blockIdx, threadIdx, blockDim, and gridDim.' },
  { slug: 'host-vs-device', term: 'Host vs. Device', category: 'gpu-cuda', voiceTemplate: 'structure', definition: 'Host and device are CUDA\'s terms for the CPU and GPU respectively, each with its own separate memory space (system RAM versus device VRAM); code on the host orchestrates the program and launches kernels, while code on the device executes those kernels, and data must be explicitly copied across the boundary between the two memory spaces.' },
  { slug: 'register-file', term: 'Register File', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'The register file is the fastest, per-thread storage on a streaming multiprocessor: it holds each thread\'s private working values so the thread can read and write them in a single cycle without touching shared or global memory, and its fixed per-SM capacity is divided among all resident threads, which is why register usage per thread limits how many threads can run concurrently.' },
  { slug: 'shared-memory', term: 'Shared Memory', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Shared memory is a fast, on-chip scratchpad allocated per thread block, so that all threads in the block can write intermediate results into it and read each other\'s data far faster than round-tripping through global memory — this is the mechanism kernels like Flash Attention use to keep tiles of data resident on-chip instead of reloading them from HBM.' },
  { slug: 'global-memory', term: 'Global Memory (HBM)', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Global memory (high-bandwidth memory, HBM) is the GPU\'s large off-chip memory pool that every thread on every streaming multiprocessor can read and write, so it holds the full input and output tensors a kernel operates on; it has far higher capacity than on-chip SRAM but much higher latency and lower bandwidth per access, which makes minimizing round-trips to it a primary optimization target.' },
  { slug: 'memory-hierarchy-gpu', term: 'GPU Memory Hierarchy', category: 'gpu-cuda', voiceTemplate: 'structure', definition: 'The GPU memory hierarchy arranges storage in tiers of decreasing speed and increasing capacity — per-thread registers, per-block shared memory/L1, chip-wide L2 cache, and off-chip global memory (HBM) — so that a kernel\'s performance depends on how much of its working data it can keep resident in the faster, smaller tiers instead of repeatedly reading from the slower, larger ones.' },
  { slug: 'occupancy', term: 'Occupancy', category: 'gpu-cuda', voiceTemplate: 'constraint', definition: 'Occupancy is a constraint on how many warps can be resident on a streaming multiprocessor at once, measured as the ratio of active warps to the maximum the hardware supports, and it is bounded by whichever per-SM resource — registers, shared memory, or thread-block slots — a kernel\'s configuration consumes first.' },
  { slug: 'warp-divergence', term: 'Warp Divergence', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Warp divergence occurs when threads within the same warp take different branches of a conditional, so the hardware serializes execution — running each distinct branch path in turn while masking off the threads that don\'t take it — which converts what should be parallel work back into sequential steps for that warp.' },
  { slug: 'memory-coalescing', term: 'Memory Coalescing', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Memory coalescing is the hardware\'s combination of multiple threads\' simultaneous global-memory accesses into a single wide transaction, so that when threads in a warp read or write contiguous, aligned addresses, one memory transaction serves them all instead of many separate ones, directly raising effective memory bandwidth.' },
  { slug: 'bank-conflict', term: 'Bank Conflict', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'A bank conflict happens when multiple threads in a warp access different addresses that map to the same shared-memory bank in the same cycle, so the hardware serializes those accesses instead of servicing them in parallel, which turns what should be a single-cycle shared-memory read or write into several sequential ones.' },
  { slug: 'tensor-memory-accelerator', term: 'Tensor Memory Accelerator (TMA)', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'The Tensor Memory Accelerator is dedicated hardware that takes a bulk data-movement request between global memory and shared memory and executes it asynchronously off the compute path, so tensor cores can keep issuing matrix operations on already-resident tiles while the next tile\'s transfer happens in the background, overlapping data movement with compute instead of stalling on it.' },
  { slug: 'nvlink', term: 'NVLink', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'NVLink is a proprietary point-to-point interconnect built specifically to connect GPUs to each other and to the CPU, so it carries only that device-to-device traffic on dedicated links rather than sharing a bus with other system peripherals, giving it substantially higher bandwidth and lower latency than a general-purpose interconnect like PCIe.' },
  { slug: 'pcie', term: 'PCIe', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'PCIe (Peripheral Component Interconnect Express) is the general-purpose bus that connects the GPU, network cards, and storage to the CPU, so it routes traffic for every attached device over shared lanes rather than a dedicated GPU-to-GPU path, which makes it lower-bandwidth and more contention-prone than a purpose-built interconnect like NVLink.' },
  { slug: 'nccl', term: 'NCCL', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'NCCL (NVIDIA Collective Communications Library) takes a collective operation request — such as AllReduce or Broadcast — and an underlying hardware topology, and selects and executes the fastest communication pattern for it, choosing ring or tree algorithms and routing over NVLink where available and falling back to PCIe otherwise, so applications don\'t hand-implement multi-GPU communication themselves.', relatedSlugs: ['all-reduce', 'nvlink'] },
  { slug: 'all-reduce', term: 'AllReduce', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'AllReduce takes a separate partial value computed independently on every GPU, combines them all with a reduction operation such as sum, and writes the identical combined result back to every GPU, so that operations like averaging gradients across data-parallel workers after a backward pass leave every device with the same updated value without any device ending up with a different one.', relatedSlugs: ['nccl'] },
  { slug: 'ring-vs-tree-collectives', term: 'Ring vs. Tree Collectives', category: 'gpu-cuda', voiceTemplate: 'structure', definition: 'Ring and tree are two topologies NCCL arranges GPUs into for collective operations: a ring passes data around a closed loop so every link stays active simultaneously, favoring bandwidth on large messages, while a tree routes data up through parent nodes toward a root in a logarithmic number of steps, favoring latency on small messages — NCCL picks between them adaptively based on message size and topology.' },
  { slug: 'data-parallelism', term: 'Data Parallelism', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Data parallelism replicates the full model onto every device and shards the training batch across them, so each device computes gradients on its own slice of data and an AllReduce combines those gradients into a shared update; it is the simplest parallelism strategy but its per-device activation memory still scales with local batch size, and it stops working once the model itself no longer fits on a single device.' },
  { slug: 'tensor-parallelism', term: 'Tensor Parallelism', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Tensor parallelism shards an individual layer\'s weight matrix across devices — splitting it column-wise or row-wise — so each device holds and computes only a slice of that layer, then synchronizes partial results with the other devices inside every forward and backward pass; that per-layer synchronization requires high-bandwidth, low-latency interconnect, which is why it is generally kept within a single node.' },
  { slug: 'pipeline-parallelism', term: 'Pipeline Parallelism', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Pipeline parallelism shards the model by layer across devices, assigning each device a contiguous stage, and streams micro-batches of data through those stages in sequence, so communication is coarser — only activations between adjacent stages — which tolerates slower cross-node interconnects but introduces idle "bubble" time unless enough micro-batches are in flight to keep every stage busy.' },
  { slug: 'mixed-precision', term: 'Mixed Precision (bf16/fp16/fp8)', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Mixed precision runs the bulk of a model\'s arithmetic in a narrower floating-point format — bf16, fp16, or fp8 — while keeping a master copy of weights and optimizer state in a higher-precision format, so the narrower format converts memory bandwidth and compute time savings into throughput while the higher-precision master copy absorbs accumulation error that would otherwise compound into divergence over long training runs.' },
  { slug: 'flash-attention', term: 'Flash Attention', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Flash Attention takes the standard attention computation and restructures it to process query, key, and value matrices tile by tile inside on-chip SRAM, maintaining running softmax statistics (a running max and running sum of exponentials) across tiles instead of materializing the full N×N score matrix in HBM, so it produces mathematically identical output while eliminating the repeated HBM writes and reads that make standard attention memory-bound rather than compute-bound at long context lengths.', relatedSlugs: ['self-attention', 'shared-memory'] },
  { slug: 'kv-cache', term: 'KV Cache', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'The KV cache stores the key and value vectors computed for every previously generated token, so that during autoregressive generation each new token\'s query only needs to attend against the cached keys and values instead of recomputing them, turning per-step attention from a matrix-matrix product over the whole sequence into a matrix-vector product against the cache — trading memory consumption, which grows with sequence length, for eliminated recomputation.' },
  { slug: 'paged-attention', term: 'Paged Attention', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Paged attention takes the KV cache and allocates its storage in fixed-size, non-contiguous pages rather than one contiguous block per sequence, so memory is claimed on demand as a sequence grows instead of being reserved upfront for a worst-case length, which removes the fragmentation and over-allocation that a contiguous KV cache forces when serving many requests of varying, unpredictable length.', relatedSlugs: ['kv-cache'] },
  { slug: 'quantization', term: 'Quantization', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Quantization takes weights or activations stored in a higher-precision numeric format and maps them to a lower-precision format such as INT8 or INT4 using a computed scale (and, for asymmetric schemes, a zero-point), so the resulting tensor occupies less memory and computes faster while the calibration step — static or dynamic, symmetric or asymmetric — determines how much accuracy that mapping trades away.' },
  { slug: 'mixture-of-experts', term: 'Mixture of Experts (MoE)', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Mixture of Experts replaces a single dense feed-forward layer with several identically-shaped feed-forward networks ("experts") plus a router, so that for each token the router scores every expert, selects only the top-k highest-scoring ones, and combines their weighted outputs — letting total parameter count scale into the trillions while the compute per token stays bounded to whatever fraction of experts are actually activated.' },
  { slug: 'gemm-vs-gemv', term: 'GEMM vs. GEMV', category: 'gpu-cuda', voiceTemplate: 'structure', definition: 'GEMM (general matrix-matrix multiply) and GEMV (general matrix-vector multiply) are the two arithmetic shapes that transformer training and inference reduce to: training processes many tokens at once, so attention and projections become matrix-matrix products with high arithmetic intensity that keep compute units busy, while single-token autoregressive inference multiplies one query vector against cached weights or keys, producing low arithmetic intensity work that is bound by how fast data can be loaded rather than by how fast it can be multiplied.' },
  { slug: 'compute-bound-vs-memory-bound', term: 'Compute-Bound vs. Memory-Bound', category: 'gpu-cuda', voiceTemplate: 'structure', definition: 'A kernel is compute-bound when its execution time is limited by how fast its arithmetic units can retire floating-point operations, and memory-bound when it is instead limited by how fast data can move between off-chip HBM and on-chip SRAM regardless of how little math is done on it; profiling a workload against this distinction — rather than assuming from FLOP count alone — determines whether the productive optimization is faster arithmetic or fewer, larger memory transfers.' },
  { slug: 'jit-compilation-cuda', term: 'JIT Compilation', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'Just-in-time compilation takes intermediate device code — PTX — and compiles it down to the specific target GPU\'s native machine code at load time or first run rather than at build time, so the same distributed binary can run on GPU architectures released after it was compiled, at the cost of a one-time compilation delay on that first execution.' },
  { slug: 'ptx', term: 'PTX', category: 'gpu-cuda', voiceTemplate: 'mechanism', definition: 'PTX (Parallel Thread Execution) is a stable, architecture-independent intermediate instruction set that the CUDA compiler emits from device source code, so that a single compiled artifact can be JIT-compiled down to the native machine code of whatever specific GPU architecture it eventually runs on, instead of being tied to one generation of hardware.' },
];
