/**
 * mlops-infra glossary terms.
 *
 * Ledger populated in Phase 1 (slug/term/category/voiceTemplate only).
 * `definition` fields are filled in Phase 2 by an isolated content subagent
 * — see plan §7. Source lineage: scratchpad/glossary-sources/{ops,
 * system_design_MLE,model}.txt, extracted from:
 *   public/excalidraw/ops.excalidraw (AI/ML slice)
 *   public/excalidraw/system_design_MLE.excalidraw @ 6541e2c48a864b1fc9fb8a7f12fcfe13976bde5b (ch09/ch10)
 *   public/excalidraw/model.excalidraw (ML Engineering best-practices frame)
 *
 * Deployment mechanisms that are NOT ML-specific (blue-green, canary as
 * general concepts) live once in systemsDesign.ts — reference them via
 * relatedSlugs rather than redefining.
 */

import type { GlossaryTerm } from './types';

export const GLOSSARY_TERMS_MLOPS_INFRA: GlossaryTerm[] = [
  { slug: 'feature-store', term: 'Feature Store', category: 'mlops-infra', voiceTemplate: 'structure', definition: 'A feature store is a shared service that computes and stores feature values once, then serves that same feature-transformation logic to both the training pipeline and the online serving path. By making offline and online reads pull from a single source of truth, it establishes the guarantee that a feature carries the same definition and value regardless of which system consumes it, closing the gap where training and serving code silently diverge.' },
  { slug: 'model-registry', term: 'Model Registry', category: 'mlops-infra', voiceTemplate: 'structure', definition: 'A model registry is a versioned catalog that records every trained model artifact alongside the data version, code commit, and hyperparameters that produced it, and tracks its stage as it moves from staging to production to archived. It establishes a single authoritative record of which model is currently serving predictions and what would need to be restored to roll back to a prior one.' },
  { slug: 'experiment-tracking', term: 'Experiment Tracking', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: "Experiment tracking automatically logs a training run's code version, dataset version, hyperparameters, and resulting metrics each time a model is trained, so any past result can be reproduced or compared against later runs. It turns model development from an ad hoc series of trials into an auditable, comparable record." },
  { slug: 'training-serving-skew', term: 'Training-Serving Skew', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: "Training-serving skew occurs when the feature values a model sees at inference time differ from the feature values it was trained on, typically because separate code paths compute features offline in batch and online in real time, or because of time-window mismatches and point-in-time label leakage in the training pipeline. The mismatch degrades production accuracy without changing the model itself, which is why it is mitigated by sharing one feature-transformation implementation across training and serving rather than maintaining two.", relatedSlugs: ['feature-store'] },
  { slug: 'shadow-deployment', term: 'Shadow Deployment', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: "Shadow deployment runs a candidate model in parallel with the production model on live traffic, generating predictions that are logged for comparison but never returned to users. It transforms real production input into a risk-free evaluation of a new model's latency, stability, and output distribution before that model is allowed to affect anyone.", relatedSlugs: ['champion-challenger', 'canary-deployment'] },
  { slug: 'champion-challenger', term: 'Champion-Challenger', category: 'mlops-infra', voiceTemplate: 'structure', definition: 'Champion-challenger is an ongoing relationship in which one model, the champion, serves production traffic while one or more challenger models are continuously evaluated against it, rather than a one-time launch gate. A challenger only replaces the champion once it demonstrably outperforms it, which keeps model promotion an evidence-based, rolling process instead of a single deploy decision.', relatedSlugs: ['shadow-deployment', 'ab-testing-ml'] },
  { slug: 'online-vs-batch-prediction', term: 'Online vs. Batch Prediction', category: 'mlops-infra', voiceTemplate: 'structure', definition: 'Online and batch prediction are two serving relationships between a model and its consumers: online prediction computes a result synchronously at request time against live feature lookups, while batch prediction precomputes results for many inputs on a fixed schedule and serves them from storage. The choice trades latency and freshness against throughput and cost, and many production systems combine both, using batch-precomputed results with an online fallback or re-ranking step.' },
  { slug: 'continual-learning', term: 'Continual Learning', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: 'Continual learning is the ongoing process of retraining a deployed model as new data arrives, so its parameters keep tracking a real world that changes after the model was first trained. It is triggered rather than constant, by a schedule, a monitored performance drop, or an accumulated volume of new labeled data, because retraining on every new example risks compute waste and catastrophic forgetting.', relatedSlugs: ['stateless-vs-stateful-training'] },
  { slug: 'stateless-vs-stateful-training', term: 'Stateless vs. Stateful Training', category: 'mlops-infra', voiceTemplate: 'structure', definition: "Stateless and stateful training are two relationships between a retraining run and the model that preceded it: stateless training discards the prior model and fits a new one from scratch on the full dataset, while stateful training loads the previous model's weights into memory and continues training on only the new data. Stateful training is cheaper per retrain but requires infrastructure that supports resuming a model's internal state end to end, and it compounds drift over time unless periodically reset with a full stateless retrain." },
  { slug: 'model-versioning', term: 'Model Versioning', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: "Model versioning assigns a distinct, traceable identifier to each trained model artifact, binding it to the exact data, code, and hyperparameters used to produce it. Because a model is treated as data plus code plus configuration rather than a single binary, versioning is what makes a specific past model reproducible and safely restorable later.", relatedSlugs: ['model-registry'] },
  { slug: 'continuous-training', term: 'Continuous Training (CT)', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: 'Continuous training is an automated pipeline that retrains, evaluates, and republishes a model without manual intervention whenever a retraining trigger fires. It turns model updates from an ad hoc, person-dependent process into a repeatable step in the deployment pipeline, reducing the risk that retraining logic drifts out of sync with what actually runs in production.' },
  { slug: 'model-artifact', term: 'Model Artifact', category: 'mlops-infra', voiceTemplate: 'structure', definition: 'A model artifact is the packaged output of a training run: the serialized weights or parameters plus the metadata needed to reproduce and serve them, including the data version, code commit, and preprocessing pipeline it depends on. Without that attached lineage the artifact is just a binary, one that cannot be reliably reproduced, audited, or rolled back to.' },
  { slug: 'retraining-trigger', term: 'Retraining Trigger', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: 'A retraining trigger is the explicit condition that initiates a new training run, commonly a fixed schedule, a monitored metric crossing a performance threshold, or a set volume of newly accumulated labeled data. Naming the trigger explicitly, rather than retraining on an implicit or ad hoc basis, is what makes continual learning an observable and debuggable process instead of a guess.' },
  { slug: 'rollback-strategy-ml', term: 'Rollback Strategy', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: 'A rollback strategy for ML defines how a production system reverts from a currently serving model back to a known-good prior version when the current one regresses, relying on the model registry to identify exactly which version was previously in production and how to restore it. Treating rollback as a first-class deployment capability, tested and automatable, rather than an afterthought is what keeps a bad model launch a contained incident instead of a prolonged outage.', relatedSlugs: ['model-registry'] },
  { slug: 'containerized-model-serving', term: 'Containerized Model Serving', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: 'Containerized model serving packages a trained model together with its runtime, dependencies, and inference code into a single immutable image, which is then deployed and scaled as a unit by a container orchestrator. Packaging this way turns model rollout into rebuilding and redeploying an image rather than patching a running service, which eliminates configuration drift between what was tested and what serves traffic.' },
  { slug: 'model-card', term: 'Model Card', category: 'mlops-infra', voiceTemplate: 'structure', definition: "A model card is a structured document attached to a specific model version that records its intended use cases, training data characteristics, evaluation performance, and known limitations. It establishes an explicit contract between the team that built a model and the teams that consume or approve it, so decisions to deploy or restrict a model are made against documented evidence rather than assumed behavior." },
  { slug: 'ab-testing-ml', term: 'A/B Testing', category: 'mlops-infra', voiceTemplate: 'mechanism', definition: 'A/B testing for ML routes randomized, non-overlapping slices of real traffic to a challenger model and the current production model, then compares them on a predefined business metric with statistical significance rather than an eyeballed dashboard. It requires a clearly defined randomization unit and guardrail metrics up front, and it is the stage in a shadow-canary-A/B rollout sequence that catches business-impact regressions the earlier, lower-traffic stages cannot.', relatedSlugs: ['champion-challenger'] },
  { slug: 'pipeline-orchestration-ml', term: 'ML Pipeline Orchestration', category: 'mlops-infra', voiceTemplate: 'structure', definition: 'ML pipeline orchestration coordinates the data, feature, training, evaluation, and deployment stages of a model as a single versioned, deployable unit, rather than as independently scheduled ETL jobs. Because a model is data plus code plus configuration, the orchestrator must version and reproduce all three together, which is what distinguishes it from generic workflow DAGs that only track task completion.' },
];
