/**
 * systems-design glossary terms.
 *
 * Ledger populated in Phase 1 (slug/term/category/voiceTemplate only).
 * `definition` fields are filled in Phase 2 by an isolated content subagent
 * — see plan §7. Source lineage: scratchpad/glossary-sources/{design,general,
 * frontend,backend,ops}.txt, extracted from:
 *   public/excalidraw/design.excalidraw   @ 04b1d4e649058ecea338cc0d50e91b66adb4fa5d
 *   public/excalidraw/general.excalidraw  @ 7b1fd23ef8e2c0930f6ba8b2e4e69e5b811b5cea
 *   public/excalidraw/frontend.excalidraw @ a68759f3c256871ce4759b76511fe9630231c9ae
 *   public/excalidraw/backend.excalidraw  @ 04b1d4e649058ecea338cc0d50e91b66adb4fa5d
 *   public/excalidraw/ops.excalidraw      @ 04b1d4e649058ecea338cc0d50e91b66adb4fa5d (deployment/IaC slice only)
 *
 * SLI/SLO/SLA/error-budget are deliberately NOT defined here — per plan §1
 * they're defined once under evaluation-observability; reference them via
 * relatedSlugs instead of redefining.
 */

import type { GlossaryTerm } from './types';

export const GLOSSARY_TERMS_SYSTEMS_DESIGN: GlossaryTerm[] = [
  { slug: 'cap-theorem', term: 'CAP Theorem', category: 'systems-design', voiceTemplate: 'constraint', definition: 'CAP theorem states that a distributed system experiencing a network partition can guarantee at most one of consistency or availability, not both, while partition tolerance itself is treated as a given for any system that spans multiple nodes. It bounds the choice at the moment nodes can\'t communicate: reject requests to stay consistent, or keep serving and risk returning stale data.' },
  { slug: 'circuit-breaker', term: 'Circuit Breaker', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'A circuit breaker tracks the failure rate of calls to a downstream dependency and, once failures cross a threshold, trips open and fails fast without attempting the call, protecting the caller from wasted latency and containing cascading failure. After a cooldown it half-opens to probe the dependency with a small number of requests, closing again only if those succeed.' },
  { slug: 'bulkhead-pattern', term: 'Bulkhead Pattern', category: 'systems-design', voiceTemplate: 'structure', definition: 'The bulkhead pattern partitions resources — thread pools, connection pools, compute — per downstream dependency, so a failing or slow dependency can only exhaust its own allocation rather than starve requests to unrelated dependencies. It trades some resource utilization for isolation, containing the blast radius of a single failure to the partition it occurred in.' },
  { slug: 'exponential-backoff', term: 'Exponential Backoff', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Exponential backoff increases the delay between successive retry attempts geometrically instead of retrying at a fixed interval, so a struggling downstream dependency isn\'t hit with sustained retry pressure while it recovers. It\'s typically paired with random jitter and a maximum retry ceiling so that many clients backing off in sync don\'t collapse back into a synchronized retry storm.' },
  { slug: 'feature-flags', term: 'Feature Flags', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'A feature flag gates a code path behind a runtime-configurable toggle, decoupling the deployment of code from the release of the behavior it enables. This lets a change ship to production dark, then be enabled for a specific cohort or rolled back instantly without a redeploy.' },
  { slug: 'b-tree-index', term: 'B-Tree Index', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'A B-tree index organizes keys in a balanced, sorted tree of fixed-size nodes so lookups, range scans, and ordered traversal all resolve in logarithmic time relative to table size. It stays balanced on insert and delete, which is why it\'s the default index structure for read-heavy workloads that need both equality lookups and ordered range queries.' },
  { slug: 'lsm-tree', term: 'LSM-Tree', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'An LSM-tree accepts writes by appending them to an in-memory buffer that\'s periodically flushed to disk as an immutable sorted file, then merges those files together in the background. It trades read amplification — a lookup may need to check multiple files — for write throughput, since writes never require the in-place random disk access a B-tree needs.', relatedSlugs: ['b-tree-index'] },
  { slug: 'sharding', term: 'Sharding', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Sharding partitions a dataset across multiple database instances by a shard key, so no single node has to store or serve the entire dataset. Each shard holds a disjoint slice of the data, which scales write and storage capacity roughly linearly but pushes cross-shard queries and joins onto the application layer.' },
  { slug: 'replication', term: 'Replication', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Replication maintains copies of the same data across multiple nodes, typically one primary that accepts writes and one or more replicas that receive a continuous stream of those writes. Synchronous replication waits for replica acknowledgment before confirming a write, trading latency for durability; asynchronous replication confirms immediately and lets replicas catch up, trading a lag window for lower write latency and more read capacity.' },
  { slug: 'consistent-hashing', term: 'Consistent Hashing', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Consistent hashing maps both data keys and shard nodes onto the same hash ring, so a key is owned by the first node found clockwise from its hash position. Adding or removing a node only remaps the keys between it and its neighbor on the ring, instead of the wholesale reshuffling a naive modulo-based scheme would require.', relatedSlugs: ['sharding'] },
  { slug: 'acid-properties', term: 'ACID Properties', category: 'systems-design', voiceTemplate: 'constraint', definition: 'ACID bounds what a transaction guarantees: atomicity (all-or-nothing execution), consistency (only valid states are reached), isolation (concurrent transactions don\'t observe each other\'s intermediate state), and durability (a committed write survives a crash). These four guarantees define the contract a relational database offers for a single transaction, at the cost of coordination overhead that limits horizontal write scale.' },
  { slug: 'base-properties', term: 'BASE Properties', category: 'systems-design', voiceTemplate: 'constraint', definition: 'BASE — Basically Available, Soft state, Eventually consistent — bounds the weaker guarantee many horizontally-scaled distributed databases offer in place of ACID: the system stays available under partition and node failure, its state may be in flux, and replicas converge to the same value only after enough time passes without new writes. It\'s the accepted tradeoff for systems that prioritize availability and write throughput over immediate consistency.', relatedSlugs: ['acid-properties'] },
  { slug: 'database-normalization', term: 'Database Normalization', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Database normalization restructures a relational schema into a series of forms that progressively eliminate redundant data, decomposing tables so each fact is stored in exactly one place and linked by foreign keys. It reduces update anomalies at the cost of requiring joins to reassemble related data at read time.' },
  { slug: 'cqrs', term: 'CQRS', category: 'systems-design', voiceTemplate: 'structure', definition: 'CQRS separates the model that handles writes — commands, enforcing invariants — from the model that serves reads — queries, often denormalized for a specific access pattern — so each side can be scaled, optimized, and evolved independently. It\'s applied when read and write access patterns diverge enough that a single shared model becomes a bottleneck for one of them.' },
  { slug: 'event-sourcing', term: 'Event Sourcing', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Event sourcing stores state changes as an append-only, ordered log of immutable events rather than persisting only current state; the current state is derived by replaying those events, and any past state can be reconstructed by replaying up to that point. This gives a full audit trail and time-travel replay but pushes complexity onto the projections that read the log and onto handling event-schema evolution over time.', relatedSlugs: ['cqrs'] },
  { slug: 'saga-pattern', term: 'Saga Pattern', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'The saga pattern coordinates a transaction that spans multiple services as a sequence of local transactions, each with a corresponding compensating action that undoes it if a later step fails. Choreography lets each service react to events independently; orchestration uses a central coordinator to drive each step, trading decoupling for a clearer, more debuggable execution path.' },
  { slug: 'microservices', term: 'Microservices', category: 'systems-design', voiceTemplate: 'structure', definition: 'Microservices structure a system as a set of independently deployable services, each owning its own data store and API, communicating over the network rather than through in-process function calls. The boundary between services is a deployment and ownership boundary as much as a technical one, which is why service boundaries tend to mirror organizational team boundaries.', relatedSlugs: ['monolith', 'conways-law'] },
  { slug: 'monolith', term: 'Monolith', category: 'systems-design', voiceTemplate: 'structure', definition: 'A monolith structures an application as a single deployable unit where modules share one codebase, process, and often one database, communicating through in-process function calls rather than the network. It sacrifices independent scaling and deployment of individual components in exchange for simpler local development and lower operational overhead.', relatedSlugs: ['microservices'] },
  { slug: 'bounded-context', term: 'Bounded Context', category: 'systems-design', voiceTemplate: 'structure', definition: 'A bounded context is a boundary within which a domain model and its terminology are internally consistent and authoritative — the same term can mean something different in another bounded context without conflict, because each context owns its own model rather than sharing one global model across the system. It\'s the unit that a microservice or module boundary is typically drawn around.' },
  { slug: 'strangler-fig-pattern', term: 'Strangler Fig Pattern', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'The strangler fig pattern migrates a legacy system incrementally by routing individual pieces of functionality to a new implementation one at a time, while the old system continues to serve everything not yet migrated. Traffic shifts feature by feature until the legacy system handles nothing and can be retired, avoiding a single high-risk cutover.' },
  { slug: 'sidecar-pattern', term: 'Sidecar Pattern', category: 'systems-design', voiceTemplate: 'structure', definition: 'The sidecar pattern deploys a helper process alongside a service instance — sharing its lifecycle and network namespace but running as a separate process — to handle cross-cutting concerns like proxying, TLS termination, or metrics collection without embedding that logic in the service\'s own code. This lets infrastructure concerns be upgraded and reused independently of the application code sitting next to them.' },
  { slug: 'conways-law', term: "Conway's Law", category: 'systems-design', voiceTemplate: 'structure', definition: "Conway's Law observes that a system's architecture tends to mirror the communication structure of the organization that built it, because the boundaries across which teams must coordinate become the boundaries drawn into the software. Deliberately aligning team ownership to a desired service boundary is a way of using this relationship rather than fighting it." },
  { slug: 'cache-aside', term: 'Cache-Aside', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Cache-aside has the application check the cache first on a read; on a miss, it fetches from the source of truth, populates the cache, and returns the result, so the cache is only ever filled lazily by real read traffic. Because population is reactive, the system degrades to hitting the underlying store directly if the cache is unavailable, at the cost of every cold key paying a full miss penalty once.' },
  { slug: 'rate-limiting', term: 'Rate Limiting', category: 'systems-design', voiceTemplate: 'constraint', definition: 'Rate limiting bounds the number of requests a client can make within a given time window, rejecting or delaying requests beyond it to protect a service from being overwhelmed by a single caller. The bound can permit bursts up to a fixed capacity or enforce a strict count within a rolling window, trading burst tolerance for precision depending on which algorithm is used.' },
  { slug: 'message-broker', term: 'Message Broker', category: 'systems-design', voiceTemplate: 'mechanism', definition: "A message broker sits between producers and consumers, accepting messages from producers and durably queuing them until consumers process them — decoupling the two in time and failure domain, since a producer doesn't need a consumer to be available or fast to keep publishing. This lets consumers process asynchronously, scale independently, and retry failed processing without blocking the producer." },
  { slug: 'api-versioning', term: 'API Versioning', category: 'systems-design', voiceTemplate: 'structure', definition: 'API versioning encodes which contract version a client is targeting — typically in the URI path or a request header — so a breaking change to a request or response shape can be introduced as a new version while existing clients keep working against the old one. It establishes an explicit compatibility boundary between the API\'s evolution and the point-in-time contract any given client depends on.' },
  { slug: 'idempotency-key', term: 'Idempotency Key', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'An idempotency key is a client-generated unique identifier attached to a non-idempotent request so that if the request is retried after a timeout or dropped response, the server can recognize the duplicate and return the original result instead of executing the operation again. It shifts responsibility for safe retries from "the operation happens to be repeatable" to "the server explicitly deduplicates by key."' },
  { slug: 'connection-pooling', term: 'Connection Pooling', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Connection pooling maintains a bounded set of pre-established, reusable connections to a downstream resource — most commonly a database — instead of opening and tearing down a new connection per request. This amortizes connection setup cost and keeps the number of concurrent connections a shared resource must handle within a known, tunable limit.' },
  { slug: 'n-plus-one-query', term: 'N+1 Query', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'The N+1 query problem occurs when code fetches a list of N parent records with one query, then issues a separate query per record to fetch related data — N+1 round trips to the database instead of one or two. It\'s fixed by eagerly loading the related data in a single joined or batched query up front instead of lazily fetching it per record.' },
  { slug: 'load-balancing', term: 'Load Balancing', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Load balancing distributes incoming requests across a pool of service instances according to a routing algorithm — round-robin, least-connections, or a hash of some request attribute — so no single instance is overwhelmed while others sit idle. It typically also removes unhealthy instances from rotation based on health checks, so traffic is only routed to instances known to be able to serve it.' },
  { slug: 'blue-green-deployment', term: 'Blue-Green Deployment', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Blue-green deployment runs two identical production environments — one live, one idle — deploys the new version to the idle environment, and cuts traffic over to it all at once once it\'s verified. Rollback is just cutting traffic back to the still-running previous environment, at the cost of running two full-size environments simultaneously during the switch.', relatedSlugs: ['canary-deployment'] },
  { slug: 'canary-deployment', term: 'Canary Deployment', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Canary deployment routes a small percentage of production traffic to a new version alongside the existing version, monitors error rates and latency on that slice, and expands the percentage only if the new version\'s metrics stay healthy. This limits the blast radius of a bad release to a fraction of real users instead of exposing everyone at once.', relatedSlugs: ['blue-green-deployment'] },
  { slug: 'infrastructure-as-code', term: 'Infrastructure as Code', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Infrastructure as code defines the desired state of infrastructure — networks, compute, permissions — in declarative, version-controlled configuration that a tool reconciles against actual infrastructure to make it match. This replaces manual console or CLI changes with a reproducible, auditable process, so drift can be detected by diffing live state against the declared source of truth.' },
  { slug: 'containerization', term: 'Containerization', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Containerization packages an application together with its runtime dependencies and filesystem into a single immutable image that runs identically across environments, sharing the host OS kernel while staying isolated in its own process and filesystem namespace. This eliminates environment-to-environment inconsistency and lets a scheduler place, scale, and restart instances without regard to the underlying host\'s specific configuration.' },
  { slug: 'service-mesh', term: 'Service Mesh', category: 'systems-design', voiceTemplate: 'structure', definition: 'A service mesh is a dedicated infrastructure layer, typically implemented as a sidecar proxy deployed alongside every service instance, that handles service-to-service concerns — mTLS, retries, load balancing, traffic routing, telemetry — outside of the application code itself. It centralizes network-level policy and observability at the platform layer instead of requiring every service to implement it independently.' },
  { slug: 'server-side-rendering', term: 'Server-Side Rendering (SSR)', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Server-side rendering generates the full HTML for a page on the server for each incoming request, sending a populated document to the client rather than an empty shell that renders after JavaScript loads. This improves first-paint speed and search-engine visibility for dynamic content, at the cost of server compute per request and a hydration step to attach interactivity client-side.' },
  { slug: 'static-site-generation', term: 'Static Site Generation (SSG)', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Static site generation pre-renders every page into HTML at build time, before any request arrives, so serving a page at runtime is just returning a static file with no server compute involved. It produces the fastest possible response time, but content is only as fresh as the last build, since pages don\'t reflect data changes until the site is rebuilt.' },
  { slug: 'client-side-rendering', term: 'Client-Side Rendering (CSR)', category: 'systems-design', voiceTemplate: 'mechanism', definition: "Client-side rendering ships a mostly-empty HTML shell plus a JavaScript bundle, and the browser fetches data and renders the page's content only after that bundle downloads and executes. It pushes rendering work onto the client, enabling highly interactive, app-like behavior after load, at the cost of delayed first meaningful paint and weaker search-engine visibility." },
  { slug: 'incremental-static-regeneration', term: 'Incremental Static Regeneration (ISR)', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Incremental static regeneration serves a statically-generated page from cache like SSG, but revalidates and regenerates it in the background after a configured interval or on-demand trigger, so subsequent requests get the updated version without a full site rebuild. It sits between SSR and SSG, giving static-file serving speed with a bounded staleness window instead of build-time-only freshness.' },
  { slug: 'core-web-vitals', term: 'Core Web Vitals', category: 'systems-design', voiceTemplate: 'constraint', definition: 'Core Web Vitals is a defined set of user-experience metrics — Largest Contentful Paint for loading speed, Interaction to Next Paint for responsiveness, and Cumulative Layout Shift for visual stability — each with a threshold separating a good experience from a degraded one. They bound how a page\'s perceived performance is measured, independent of any one implementation choice.' },
  { slug: 'code-splitting', term: 'Code Splitting', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'Code splitting breaks a JavaScript bundle into smaller chunks that load on demand — typically per route or per component — instead of shipping the entire application\'s code on initial page load. This reduces the amount of JavaScript the client must download and parse before a page becomes interactive, deferring the cost of rarely-used code until it\'s actually needed.' },
  { slug: 'oauth2-oidc', term: 'OAuth 2.0 / OIDC', category: 'systems-design', voiceTemplate: 'mechanism', definition: "OAuth 2.0 delegates authorization to an identity provider, which issues a token granting a client scoped access to a resource without the client ever handling the user's credentials directly. OpenID Connect adds a thin identity layer on top of that flow — a standardized ID token — so the same handshake can also answer who the user is, which is why the two are used together for federated login." },
  { slug: 'jwt', term: 'JWT', category: 'systems-design', voiceTemplate: 'mechanism', definition: "A JWT is a self-contained, digitally signed token that encodes claims about an identity directly in its payload, so a server can verify a request's authenticity by checking the signature and expiry without looking up session state anywhere else. This statelessness makes JWTs easy to scale horizontally, but a compromised token remains valid until it expires — it can't be revoked the way a server-side session can." },
  { slug: 'rbac', term: 'Role-Based Access Control (RBAC)', category: 'systems-design', voiceTemplate: 'structure', definition: 'Role-based access control assigns permissions to named roles rather than to individual users, then assigns users to one or more of those roles, so authorization decisions are made by checking role membership against a fixed permission set instead of evaluating per-user rules. It trades the flexibility of finer-grained models for a permission structure that\'s simple to reason about and audit.' },
  { slug: 'tls', term: 'TLS', category: 'systems-design', voiceTemplate: 'mechanism', definition: "TLS establishes an encrypted, authenticated channel between two endpoints by having them negotiate a shared session key through a handshake, using the server's certificate to prove its identity before any application data is exchanged. Every byte sent afterward is encrypted and integrity-checked, preventing an intermediary from reading or silently altering the traffic." },
  { slug: 'zero-trust-security', term: 'Zero-Trust Security', category: 'systems-design', voiceTemplate: 'structure', definition: "Zero-trust security removes the assumption that traffic originating inside a network perimeter is inherently trustworthy, and instead requires every request — internal or external — to be authenticated and authorized at each hop. It replaces a single perimeter boundary with per-connection verification, so compromising one internal component doesn't grant implicit access to everything else on the network." },
  { slug: 'race-condition', term: 'Race Condition', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'A race condition occurs when multiple threads or processes access and mutate shared state concurrently without synchronization, so the outcome depends on the unpredictable order in which their operations interleave. The result is nondeterministic behavior — correct under one timing, corrupted under another — that a mutex or other synchronization primitive prevents by serializing access to the shared state.', relatedSlugs: ['mutex'] },
  { slug: 'mutex', term: 'Mutex', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'A mutex grants exclusive access to a shared resource to exactly one thread at a time — any other thread that attempts to acquire it blocks until the holder releases it. It\'s the basic primitive for preventing race conditions on shared mutable state, at the cost of serializing any code that touches the protected resource.' },
  { slug: 'semaphore', term: 'Semaphore', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'A semaphore maintains a fixed count of available permits and lets up to that many threads hold one concurrently, blocking any additional thread until a permit is released — generalizing a mutex, which is a semaphore with a count of one, to bound concurrency rather than restrict it to a single holder. It\'s used to cap access to a resource that can safely serve more than one caller at a time but not an unbounded number.', relatedSlugs: ['mutex'] },
  { slug: 'deadlock', term: 'Deadlock', category: 'systems-design', voiceTemplate: 'structure', definition: 'A deadlock is a state where two or more threads or processes each hold a resource the other needs and wait on a resource the other holds, so none of them can proceed. It requires four conditions to hold simultaneously — mutual exclusion, hold-and-wait, no preemption, and circular wait — and breaking any one of them is enough to prevent it.' },
  { slug: 'event-loop', term: 'Event Loop', category: 'systems-design', voiceTemplate: 'mechanism', definition: 'An event loop is a single-threaded runtime construct that continuously pulls the next event or callback off a queue and executes it to completion, dispatching I/O operations to be handled asynchronously rather than blocking the thread while waiting on them. This lets a single thread handle many concurrent I/O-bound operations without the overhead of one OS thread per connection, at the cost of any long-running synchronous callback blocking every other pending event.' },
  { slug: 'backpressure', term: 'Backpressure', category: 'systems-design', voiceTemplate: 'mechanism', definition: "Backpressure is a signal a slow consumer sends back to a faster producer indicating it can't keep up, so the producer can slow down, buffer, or drop work instead of overwhelming the consumer. Without an explicit backpressure mechanism, an unbounded queue between a fast producer and a slow consumer grows without limit until memory or latency budgets are exhausted." },
  { slug: 'encapsulation', term: 'Encapsulation', category: 'systems-design', voiceTemplate: 'structure', definition: "Encapsulation bundles an object's internal state together with the operations that act on it, and restricts external code to interacting with that state only through an explicitly exposed interface rather than reaching in directly. This establishes a boundary where the internal representation can change without breaking code outside it, as long as the exposed interface's contract stays the same." },
  { slug: 'polymorphism', term: 'Polymorphism', category: 'systems-design', voiceTemplate: 'mechanism', definition: "Polymorphism lets code invoke the same operation — the same method name or interface — on objects of different underlying types, with each type's own implementation executing, without the calling code needing to know which concrete type it's dealing with. The call is resolved to the correct implementation at runtime based on the object's actual type, which is what lets calling code be written against an interface rather than a specific class." },
  { slug: 'inheritance', term: 'Inheritance', category: 'systems-design', voiceTemplate: 'structure', definition: "Inheritance establishes a hierarchical relationship where a subclass derives the fields and behavior of a parent class and can override or extend them, rather than redefining that behavior from scratch. It couples the subclass to its parent's implementation, which is why composition — assembling behavior from independent parts instead of inheriting it — is often preferred once that hierarchy grows deep or rigid." },
  { slug: 'abstraction-oop', term: 'Abstraction (OOP)', category: 'systems-design', voiceTemplate: 'structure', definition: "Abstraction establishes a boundary that exposes only the essential behavior of an object or interface — what it does — while hiding the implementation details of how it does it. Code interacts with a simplified, stable contract instead of the full complexity underneath, so the implementation can change independently of the code depending on it." },
];
