import type { BookId, DeployOpsBook } from './types';

/**
 * One registry for every book on the DeployOps reading path.
 *
 * Takeaways are inferred from each book's table of contents, publisher
 * description or author repo (`basis`), NOT from the book text, and carry a
 * `confidence`. The O'Reilly pages could not be fetched during research, so the
 * UI says so rather than implying the books were read.
 *
 * Notes on the original eight-book list (isCoreList: true):
 * - "Evals for AI" is titled "Evals for AI Engineers" (early release).
 * - "LLMs in Production" is published by Manning, not O'Reilly.
 * - "0642572422783" (Harness Engineering) is an O'Reilly product id, not an
 *   ISBN, so isbn13 is null. "Harness" means the agent harness, not an eval harness.
 * - "Hands-on LLM Serving" is titled "Hands-On LLM Serving and Optimization".
 *
 * Books with isCoreList: false (the DevOps and MLOps bridge titles) were added
 * because none of the eight covers git, CI, containers or Kubernetes. Their
 * ISBNs come from retailer and search listings, not publisher pages.
 */
export const DEPLOYOPS_BOOKS: DeployOpsBook[] = [
  // --- DevOps practice and culture ---
  {
    id: 'phoenix-project',
    title: 'The Phoenix Project',
    edition: '5th anniversary ed.',
    year: 2018,
    authors: ['Gene Kim', 'Kevin Behr', 'George Spafford'],
    publisher: 'IT Revolution',
    status: 'published',
    track: 'devops-practice',
    url: 'https://itrevolution.com/product/the-phoenix-project/',
    isbn13: '9781942788294',
    whyRead: 'A novel that makes the delivery loop felt before it is formalized: why work piles up, why unplanned work wins, and why feedback has to be fast.',
    stageIds: ['version', 'deploy', 'operate'],
    takeaways: [
      'Flow, feedback and continual learning are the three ideas underneath every practice that follows.',
      'Limiting work in progress and making work visible are what expose the real bottleneck.',
      'Unplanned work and fragile change management are the failure the lifecycle exists to prevent.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
  },
  {
    id: 'accelerate',
    title: 'Accelerate',
    year: 2018,
    authors: ['Nicole Forsgren', 'Jez Humble', 'Gene Kim'],
    publisher: 'IT Revolution',
    status: 'published',
    track: 'devops-practice',
    url: 'https://itrevolution.com/product/accelerate/',
    isbn13: '9781942788331',
    whyRead: 'The evidence for which delivery practices actually move outcomes, and where the DORA delivery metrics come from.',
    stageIds: ['verify', 'deploy', 'learn'],
    takeaways: [
      'Trunk-based development, continuous integration and test automation correlate with better delivery performance.',
      'Delivery performance is measurable: throughput and stability, tracked together rather than traded off.',
      'Culture and architecture constrain how fast a team can safely move.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
  },
  {
    id: 'devops-handbook',
    title: 'The DevOps Handbook',
    edition: '2nd ed.',
    year: 2021,
    authors: ['Gene Kim', 'Jez Humble', 'Patrick Debois', 'John Willis', 'Nicole Forsgren'],
    publisher: 'IT Revolution',
    status: 'published',
    track: 'devops-practice',
    url: 'https://itrevolution.com/product/the-devops-handbook-second-edition/',
    isbn13: '9781950508402',
    whyRead: 'The practical how-to for the lifecycle end to end: pipelines, automated testing, low-risk releases, telemetry and learning from incidents.',
    stageIds: ['version', 'build', 'verify', 'deploy', 'observe'],
    takeaways: [
      'A deployment pipeline is the mechanism that turns version control into a safe, repeatable release.',
      'Releases become low-risk when deploy is decoupled from release and change is small and frequent.',
      'Telemetry and blameless learning close the loop from production back to the next change.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
  },
  {
    id: 'site-reliability-engineering',
    title: 'Site Reliability Engineering',
    edition: '1st ed.',
    year: 2016,
    authors: ['Betsy Beyer', 'Chris Jones', 'Jennifer Petoff', 'Niall Richard Murphy'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'devops-practice',
    url: 'https://sre.google/sre-book/table-of-contents/',
    isbn13: '9781491929124',
    whyRead: 'The vocabulary and discipline of running production: SLIs, SLOs, error budgets, monitoring, incident response and release engineering.',
    stageIds: ['operate', 'observe', 'learn'],
    takeaways: [
      'An SLO and its error budget turn reliability into a number that gates release speed.',
      'Monitoring should alert on symptoms users feel, not on every internal cause.',
      'Blameless postmortems convert incidents into durable changes.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
    note: 'The full text is free online at sre.google (link above); the print edition is from O’Reilly.',
  },
  {
    id: 'kubernetes-up-and-running',
    title: 'Kubernetes: Up and Running',
    edition: '3rd ed.',
    year: 2022,
    authors: ['Brendan Burns', 'Joe Beda', 'Kelsey Hightower', 'Lachlan Evenson'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'devops-practice',
    url: 'https://www.oreilly.com/library/view/kubernetes-up-and/9781098110192/',
    isbn13: '9781098110208',
    whyRead: 'The reconcile-loop mental model made concrete: pods, services, deployments, configuration, rollouts and health probes.',
    stageIds: ['deploy', 'operate'],
    takeaways: [
      'Kubernetes continuously compares declared and actual state and acts to close the gap.',
      'Deployments, Services and probes are the building blocks of a safe rollout.',
      'Configuration and storage are separate concerns from the container image.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
    note: 'A newer edition may exist; check the publisher before buying.',
  },

  // --- Observability ---
  {
    id: 'observability-engineering',
    title: 'Observability Engineering',
    edition: '2nd ed.',
    year: 2026,
    authors: ['Charity Majors', 'Liz Fong-Jones', 'George Miranda'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'observability',
    url: 'https://www.oreilly.com/library/view/observability-engineering-2nd/9781098179915/',
    isbn13: '9781098179915',
    whyRead: 'The best foundation for the Observe stage in both specializations: asking new questions of production instead of only watching known failure modes.',
    stageIds: ['observe', 'learn'],
    takeaways: [
      'Observability means asking new questions of production without shipping new code.',
      'Instrumentation belongs in the development loop, not bolted on afterwards.',
      'SLOs and wide telemetry tie engineering work to business impact, now extended to AI workloads.',
    ],
    basis: 'publisher-description',
    confidence: 'medium',
    isCoreList: true,
  },

  // --- MLOps bridge ---
  {
    id: 'reliable-machine-learning',
    title: 'Reliable Machine Learning',
    year: 2022,
    authors: ['Cathy Chen', 'Niall Richard Murphy', 'Kranti Parisa', 'D. Sculley', 'Todd Underwood'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'ml-bridge',
    url: null,
    isbn13: '9781098106225',
    whyRead: 'The most direct bridge from SRE practice to ML in production: running models with the same reliability discipline as services.',
    stageIds: ['operate', 'observe'],
    takeaways: [
      'ML systems need SLOs and incident response the same way services do.',
      'Data and model changes are release events that deserve the same gating as code.',
      'Reliability is a property of the whole pipeline, not only the model.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
  },
  {
    id: 'designing-machine-learning-systems',
    title: 'Designing Machine Learning Systems',
    year: 2022,
    authors: ['Chip Huyen'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'ml-bridge',
    url: null,
    isbn13: '9781098107963',
    whyRead: 'End-to-end production ML before LLMs: data, training, deployment, monitoring and continual retraining.',
    stageIds: ['version', 'build', 'deploy', 'observe', 'learn'],
    takeaways: [
      'Production ML is an iterative loop, not a one-time model build.',
      'Data and feature management cause more failures than model choice.',
      'Monitoring for drift is what keeps a deployed model honest.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
  },
  {
    id: 'practical-mlops',
    title: 'Practical MLOps',
    year: 2021,
    authors: ['Noah Gift', 'Alfredo Deza'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'ml-bridge',
    url: null,
    isbn13: '9781098103019',
    whyRead: 'The CI/CD-minded, tool-level view of MLOps across the major clouds.',
    stageIds: ['build', 'verify', 'deploy'],
    takeaways: [
      'Apply DevOps automation (CI/CD, containers, monitoring) to the model lifecycle.',
      'Operationalizing a model is mostly pipeline and infrastructure work.',
      'Cloud platforms offer managed versions of the same lifecycle stages.',
    ],
    basis: 'established-reputation',
    confidence: 'medium',
    isCoreList: false,
  },

  // --- Building AI applications ---
  {
    id: 'ai-engineering',
    title: 'AI Engineering: Building Applications with Foundation Models',
    year: 2024,
    authors: ['Chip Huyen'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'ai-engineering',
    url: 'https://www.oreilly.com/library/view/ai-engineering/9781098166298/',
    isbn13: '9781098166298',
    whyRead: 'The broadest single map of building on foundation models: prompting, RAG, finetuning, evaluation, inference optimization and feedback.',
    stageIds: ['define', 'build', 'verify', 'deploy', 'learn'],
    takeaways: [
      'Evaluation gets two chapters because it is the central bottleneck of AI engineering.',
      'Adaptation escalates from prompting to RAG and agents to finetuning; pick the cheapest step that works.',
      'Inference optimization and user feedback close the loop between production and iteration.',
    ],
    basis: 'toc',
    confidence: 'medium',
    isCoreList: true,
    note: 'Also listed under ISBN 9781098166267 by some sellers; the link uses the O’Reilly id.',
  },
  {
    id: 'llmops',
    title: 'LLMOps: Managing Large Language Models in Production',
    year: 2025,
    authors: ['Abi Aryan'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'ai-engineering',
    url: 'https://www.oreilly.com/library/view/llmops/9781098154196/',
    isbn13: '9781098154196',
    whyRead: 'The MLOps lifecycle applied to LLM applications: data, adaptation, deployment, evaluation, monitoring and hardware.',
    stageIds: ['define', 'version', 'deploy', 'operate', 'observe'],
    takeaways: [
      'LLMOps is its own lifecycle layered on MLOps, not a rename of it.',
      'Reliability comes from API-first deployment plus monitoring, privacy and security as first-class concerns.',
      'Hardware and resource management are design inputs, so cost and capacity belong in the architecture.',
    ],
    basis: 'toc',
    confidence: 'low-medium',
    isCoreList: true,
  },
  {
    id: 'llms-in-production',
    title: 'LLMs in Production',
    year: 2025,
    authors: ['Christopher Brousseau', 'Matt Sharp'],
    publisher: 'Manning',
    status: 'published',
    track: 'ai-engineering',
    url: 'https://www.manning.com/books/llms-in-production',
    isbn13: '9781633437203',
    whyRead: 'A practical walk from prototype to production: integration, cost-efficient training, platform scaling, evaluation, security and operations.',
    stageIds: ['build', 'deploy', 'operate'],
    takeaways: [
      'The hard part is production, not the model.',
      'Evaluation, security and platform scaling are first-class concerns.',
      'Cost-efficient techniques are what make a deployment viable.',
    ],
    basis: 'publisher-description',
    confidence: 'low-medium',
    isCoreList: true,
    note: 'A Manning title (also available on the O’Reilly learning platform).',
  },

  // --- Evals ---
  {
    id: 'evals-for-ai-engineers',
    title: 'Evals for AI Engineers',
    year: null,
    authors: ['Shreya Shankar', 'Hamel Husain'],
    publisher: "O'Reilly",
    status: 'early-release',
    track: 'evals',
    url: 'https://www.oreilly.com/library/view/evals-for-ai/9798341660717/',
    isbn13: '9798341660717',
    whyRead: 'Evals are the CI gate for probabilistic systems: error analysis of real traces, then automated evaluators you can trust.',
    stageIds: ['verify', 'learn'],
    takeaways: [
      'Start with manual error analysis of real traces and derive metrics from observed failures.',
      'An LLM-as-judge must itself be validated against human labels.',
      'Evaluation is a continuous loop over production traces, including multi-turn sessions.',
    ],
    basis: 'toc',
    confidence: 'medium',
    isCoreList: true,
    note: 'Only part of the table of contents was visible.',
  },

  // --- Serving and optimization ---
  {
    id: 'hands-on-llm-serving',
    title: 'Hands-On LLM Serving and Optimization',
    year: 2026,
    authors: ['Chi Wang', 'Peiheng Hu'],
    publisher: "O'Reilly",
    status: 'published',
    track: 'serving',
    url: 'https://www.oreilly.com/library/view/hands-on-llm-serving/9798341621480/',
    isbn13: '9798341621480',
    whyRead: 'The mechanics of inference: prefill versus decode, the KV cache, batching, quantization and benchmark-driven optimization.',
    stageIds: ['deploy', 'operate'],
    takeaways: [
      'Cost and latency come from the autoregressive loop: prefill versus decode and the KV cache.',
      'Throughput comes from layered optimizations: continuous batching, quantization, speculative decoding and parallelism.',
      'Optimize benchmark-first, measuring each trade-off against defined metrics.',
    ],
    basis: 'toc',
    confidence: 'medium',
    isCoreList: true,
  },

  // --- Agents ---
  {
    id: 'harness-engineering',
    title: 'Harness Engineering',
    year: null,
    authors: ['Nicole Koenigstein'],
    publisher: "O'Reilly",
    status: 'early-release',
    track: 'agents',
    url: 'https://www.oreilly.com/library/view/harness-engineering/0642572422783/',
    isbn13: null,
    whyRead: 'The runtime around an LLM agent: state, tools, capability boundaries, handoff, telemetry and governance.',
    stageIds: ['operate', 'observe', 'verify'],
    takeaways: [
      'The harness, not the model, is the reliability layer of an agent system.',
      'Identity, capability boundaries and multi-agent handoff are explicit design objects.',
      'Telemetry, optimization and governance close the loop for agents.',
    ],
    basis: 'author-repo',
    confidence: 'medium',
    isCoreList: true,
    note: 'The identifier 0642572422783 is an O’Reilly product id, not an ISBN. "Harness" means the agent harness, not an eval harness.',
  },

  // --- Consolidation ---
  {
    id: 'ai-engineering-interviews',
    title: 'AI Engineering Interviews',
    year: null,
    authors: ['Mina Ghashami', 'Ali Torkamani'],
    publisher: "O'Reilly",
    status: 'early-release',
    track: 'interview',
    url: 'https://www.oreilly.com/library/view/ai-engineering-interviews/9798341623521/',
    isbn13: '9798341623521',
    whyRead: 'A consolidation check: can you explain the trade-offs aloud, from pretrained models and RAG through evaluation and theory?',
    stageIds: ['define', 'verify'],
    takeaways: [
      'The AI engineer owns the whole application stack, from pretrained models to agentic RAG.',
      'Evaluation is a first-class topic with its own chapter.',
      'Theory depth is expected: math, transformers, alignment and long-context modeling.',
    ],
    basis: 'toc',
    confidence: 'medium',
    isCoreList: true,
    note: 'Inferred from chapter titles only; the table of contents is marked not final.',
  },
];

/** Takes a raw id so callers can look up before narrowing; null for an unknown id. */
export function getBookById(id: string): DeployOpsBook | null {
  return DEPLOYOPS_BOOKS.find((book) => book.id === id) ?? null;
}

export type { BookId };
