/**
 * Glossary for the /deployops section. Terms are grouped by level and sorted
 * alphabetically (case-insensitive) within each group.
 */

import type { TermDefinition } from './types';

type TermPageLevel = 'devops' | 'ai-llm-mlops' | 'overview';

const SHARED_TERMS: TermDefinition[] = [
  { id: 'artifact', term: 'Artifact', level: 'shared', definition: 'A file or bundle that a build step produces and later steps consume, such as a container image or a trained model file. Treating it as a fixed, named output lets every later stage work on exactly the same thing.' },
  { id: 'blast-radius', term: 'Blast radius', level: 'shared', definition: 'How much of a system or how many users are affected if a change goes wrong. Releasing to a small slice first keeps the blast radius small.' },
  { id: 'determinism', term: 'Determinism', level: 'shared', definition: 'The same inputs always produce the same output. Many real systems are only partly deterministic, for example because of timestamps, random numbers or parallel timing.' },
  { id: 'drift', term: 'Drift', level: 'shared', definition: 'A slow, often unnoticed gap that opens between how a system was set up or tested and how it behaves now. It can come from changed configuration, changed data or a changed world.' },
  { id: 'feedback-loop', term: 'Feedback loop', level: 'shared', definition: 'A path that carries what happened in later stages (failures, measurements, user behavior) back to earlier decisions. Shorter loops let you find and fix mistakes sooner.' },
  { id: 'gate', term: 'Gate', level: 'shared', definition: 'A checkpoint that a change must pass before moving to the next stage, such as passing tests or an approval. If the check fails, the change stops there.' },
  { id: 'idempotent', term: 'Idempotent', level: 'shared', definition: 'An operation that leaves the system in the same state whether you run it once or several times. This makes retries and re-runs safe.' },
  { id: 'immutable', term: 'Immutable', level: 'shared', definition: 'Something that is never edited after it is created; a change means creating a new version instead. That way a given version always means the same thing.' },
  { id: 'invariant', term: 'Invariant', level: 'shared', definition: 'A condition that must stay true no matter what else changes, for example "production only runs images that passed tests". Each stage of a process exists to protect some invariant.' },
  { id: 'lifecycle', term: 'Lifecycle', level: 'shared', definition: 'The ordered stages a change passes through from idea to running software and back to lessons learned. Seeing the whole sequence helps you place where a given problem arises.' },
  { id: 'reproducibility', term: 'Reproducibility', level: 'shared', definition: 'The ability to rebuild or rerun something later and get the same result, using recorded inputs and steps. It is what lets you debug the past and trust the present.' },
];

const DEVOPS_TERMS: TermDefinition[] = [
  { id: 'twelve-factor', term: '12-factor app', level: 'devops', definition: 'A set of twelve guidelines for building apps that are easy to deploy and run in many environments, such as keeping configuration outside the code and treating logs as a stream. It is a checklist of habits, not a tool.' },
  { id: 'bake-window', term: 'Bake window', level: 'devops', definition: 'A waiting period after a release during which the team watches for problems before treating the release as safe. Some issues only appear after the new version has run for a while.' },
  { id: 'blue-green', term: 'Blue-green deployment', level: 'devops', definition: 'Running two full copies of an application, one live and one idle, and switching traffic to the new copy all at once. Rolling back means switching traffic back, at the cost of running two copies.' },
  { id: 'burn-rate', term: 'Burn rate', level: 'devops', definition: 'How fast a service is using up its error budget compared with the pace that would exactly use it up by the end of the period. A high burn rate means the target will be missed soon unless something changes.' },
  { id: 'canary', term: 'Canary', level: 'devops', definition: 'Sending a small share of real traffic to a new version first and watching how it does before widening the rollout. If metrics get worse, only that small share is affected.' },
  { id: 'correlation-id', term: 'Correlation id', level: 'devops', definition: 'A unique identifier attached to a request and passed along to every service that handles it. Searching for that id gathers all the related logs in one place.' },
  { id: 'desired-vs-actual-state', term: 'Desired vs actual state', level: 'devops', definition: 'Desired state is what you have declared you want running; actual state is what is really running right now. Many tools work by repeatedly comparing the two and fixing differences.' },
  { id: 'digest', term: 'Digest (sha256)', level: 'devops', definition: 'A fingerprint computed from the exact bytes of a file or image, so any change produces a different value. Referring to an image by digest instead of a movable tag such as "latest" guarantees you get the same contents every time.' },
  { id: 'envsubst-helm-kustomize', term: 'envsubst, Helm and Kustomize', level: 'devops', definition: 'Three ways to reuse one set of deployment files across environments. envsubst fills in placeholders from environment variables, Helm uses templates with values, and Kustomize layers patches on top of a base without templating.' },
  { id: 'error-budget', term: 'Error budget', level: 'devops', definition: 'The amount of unreliability a service is allowed while still meeting its reliability target; a 99.9% target allows 0.1% of failures. It turns "how careful should we be" into a number teams can spend on releases.' },
  { id: 'expand-contract', term: 'Expand/contract migration', level: 'devops', definition: 'A way to change a database in safe steps: first add the new structure alongside the old, move code and data over, then remove the old structure. Old and new versions of the app keep working throughout.' },
  { id: 'feature-flag', term: 'Feature flag', level: 'devops', definition: 'A switch in the code that turns a feature on or off without deploying again. It separates shipping code from exposing it to users.' },
  { id: 'gitops', term: 'GitOps', level: 'devops', definition: 'Keeping the desired state of a system in a Git repository and having an automated agent make the running system match it. Changes happen through commits, which also gives you history and an easy rollback.' },
  { id: 'hermetic-build', term: 'Hermetic build', level: 'devops', definition: 'A build that depends only on inputs it declares, with no hidden reliance on the network or the machine it runs on. It should give the same output wherever it is run.' },
  { id: 'liveness-probe', term: 'Liveness probe', level: 'devops', definition: 'A periodic check that asks whether a running program is still working or has gotten stuck. If it fails repeatedly, the platform typically restarts the program.' },
  { id: 'lockfile', term: 'Lockfile', level: 'devops', definition: 'A file that records the exact versions of every dependency that was installed. Installing from it gives the same set of packages each time instead of whatever is newest.' },
  { id: 'readiness-probe', term: 'Readiness probe', level: 'devops', definition: 'A check that asks whether a program is ready to receive traffic right now. While it fails, the platform stops sending requests to that instance but does not necessarily restart it.' },
  { id: 'reconciliation', term: 'Reconciliation', level: 'devops', definition: 'A control loop that repeatedly compares desired state with actual state and takes action to close the gap. It keeps going, so it also repairs problems that appear later.' },
  { id: 'rolling-update', term: 'Rolling update', level: 'devops', definition: 'Replacing instances of an application with a new version a few at a time, so the service stays up throughout. Old and new versions run side by side for a while.' },
  { id: 'sbom', term: 'SBOM', level: 'devops', definition: 'Software bill of materials: a list of the components and libraries that went into a piece of software. It lets you quickly check whether you are affected when a vulnerability is announced.' },
  { id: 'service-mesh', term: 'Service mesh', level: 'devops', definition: 'A layer of helper proxies next to each service that handles network concerns such as encryption, retries and traffic splitting. It lets those features be added without changing application code.' },
  { id: 'shadow-traffic', term: 'Shadow traffic', level: 'devops', definition: 'Copying real requests to a new version whose responses are discarded, so it can be tested on real load without affecting users. It must be set up carefully so copies do not cause real side effects such as duplicate payments.' },
  { id: 'sli', term: 'SLI', level: 'devops', definition: 'Service level indicator: a measurement of how well a service is doing from a user point of view, such as the fraction of requests that succeed or finish quickly.' },
  { id: 'slo', term: 'SLO', level: 'devops', definition: 'Service level objective: a target for an SLI over a time period, for example "99.9% of requests succeed over 30 days". It defines what "reliable enough" means.' },
  { id: 'startup-probe', term: 'Startup probe', level: 'devops', definition: 'A check used while a program is still starting up, giving slow starters extra time before other checks begin. It prevents a program that is merely slow to start from being restarted by mistake.' },
  { id: 'test-pyramid', term: 'Test pyramid', level: 'devops', definition: 'A guideline to have many small, fast tests, fewer tests that combine several parts, and very few full end-to-end tests. Fast tests catch most problems cheaply, while slow tests are kept for the most important paths.' },
  { id: 'trunk-based-development', term: 'Trunk-based development', level: 'devops', definition: 'A way of working where everyone merges small changes into one main branch often, instead of keeping long-lived branches. It reduces painful merges and keeps the main branch ready to release.' },
  { id: 'wide-event', term: 'Wide event', level: 'devops', definition: 'A single log record per request that carries many fields of context, such as user, version, route and timings. Having everything in one record makes it easier to slice and search when investigating problems.' },
];

const AI_LLM_MLOPS_TERMS: TermDefinition[] = [
  { id: 'activation-checkpointing', term: 'Activation checkpointing', level: 'ai-llm-mlops', definition: 'A way to save GPU memory during training by not storing some intermediate values and recomputing them when needed. It trades extra computation time for lower memory use.' },
  { id: 'agent-harness', term: 'Agent harness', level: 'ai-llm-mlops', definition: 'The code around a language model that runs it in a loop: it supplies tools, passes along results, manages context and decides when to stop. The model supplies the reasoning, and the harness supplies the surrounding machinery.' },
  { id: 'all-reduce', term: 'All-reduce', level: 'ai-llm-mlops', definition: 'A communication step where every GPU contributes its values, such as gradients, and every GPU receives the combined result, for example the sum or average. It is how GPUs keep their copies of a model in agreement.' },
  { id: 'asha', term: 'ASHA', level: 'ai-llm-mlops', definition: 'Asynchronous Successive Halving: a tuning method that starts many configurations, repeatedly stops the worst performers early, and gives the survivors more training. Being asynchronous means workers do not wait for each other.' },
  { id: 'champion-challenger', term: 'Champion/challenger', level: 'ai-llm-mlops', definition: 'Comparing a new candidate model (the challenger) against the one currently in use (the champion) on the same data or traffic. The challenger replaces the champion only if it does better.' },
  { id: 'concept-drift', term: 'Concept drift', level: 'ai-llm-mlops', definition: 'The relationship between inputs and the correct answer changes over time, so a model that was right before becomes wrong even if inputs look similar. For example, what counts as fraud shifts as fraudsters change tactics.' },
  { id: 'constrained-decoding', term: 'Constrained decoding', level: 'ai-llm-mlops', definition: 'Limiting which tokens a language model may produce at each step so the output follows a required format, such as valid JSON. It makes structured output reliable rather than just likely.' },
  { id: 'continuous-batching', term: 'Continuous batching', level: 'ai-llm-mlops', definition: 'A serving technique that lets new requests join a running group of requests, and finished ones leave, at each generation step. It keeps the GPU busy instead of waiting for the slowest request in a fixed batch.' },
  { id: 'covariate-drift', term: 'Covariate drift', level: 'ai-llm-mlops', definition: 'The kind of data a model receives changes compared with what it was trained on, even if the underlying rule linking inputs to answers has not changed. Also called data drift or input drift.' },
  { id: 'data-flywheel', term: 'Data flywheel', level: 'ai-llm-mlops', definition: 'A cycle where using a product produces data, that data improves the model, and the better model attracts more use. It only works if you actually collect, filter and feed back the useful data.' },
  { id: 'ddp', term: 'DDP', level: 'ai-llm-mlops', definition: 'Distributed Data Parallel: each GPU holds a full copy of the model and trains on a different slice of the data, then the GPUs average their gradients. It is simple and common, but each GPU must fit the whole model.' },
  { id: 'decode', term: 'Decode', level: 'ai-llm-mlops', definition: 'The phase where a language model generates its answer one token at a time, each step depending on the previous ones. It is usually limited by memory speed rather than raw computation.' },
  { id: 'embedding', term: 'Embedding', level: 'ai-llm-mlops', definition: 'A list of numbers that represents the meaning of a piece of text, image or other item, so that similar items get similar numbers. It lets software compare meaning by measuring distance.' },
  { id: 'fsdp', term: 'FSDP', level: 'ai-llm-mlops', definition: 'Fully Sharded Data Parallel: like data parallel training, but the model, gradients and optimizer state are split across GPUs and gathered only when needed. This lets models too large for one GPU be trained.' },
  { id: 'golden-set', term: 'Golden set', level: 'ai-llm-mlops', definition: 'A curated collection of example inputs with trusted expected outputs or ratings, used to check a model or prompt after every change. It acts like a regression test for AI behavior.' },
  { id: 'gradient-accumulation', term: 'Gradient accumulation', level: 'ai-llm-mlops', definition: 'Running several small batches and adding up their gradients before updating the model once. It imitates a larger batch size when memory cannot hold one.' },
  { id: 'hyperband', term: 'Hyperband', level: 'ai-llm-mlops', definition: 'A tuning method that tries many settings with a small training budget, keeps the promising ones and gives them more budget. It spends little on settings that look poor early.' },
  { id: 'inter-token-latency', term: 'Inter-token latency', level: 'ai-llm-mlops', definition: 'The average time between one generated token and the next while a model is streaming its answer. It determines how fast the text appears to flow to the reader.' },
  { id: 'ks-test', term: 'KS test', level: 'ai-llm-mlops', definition: 'Kolmogorov-Smirnov test: a statistical test that compares two sets of numeric values and measures how different their distributions are. It is often used to flag that live data no longer resembles training data.' },
  { id: 'kv-cache', term: 'KV cache', level: 'ai-llm-mlops', definition: 'Stored intermediate values (keys and values) from tokens a language model has already processed, so it does not recompute them for each new token. It speeds up generation but uses significant GPU memory that grows with context length.' },
  { id: 'lineage', term: 'Lineage', level: 'ai-llm-mlops', definition: 'A record of where a model or dataset came from: which data, code, settings and earlier versions produced it. It lets you trace a bad result back to its cause.' },
  { id: 'llm-as-judge', term: 'LLM-as-judge', level: 'ai-llm-mlops', definition: 'Using a language model to grade another model\'s outputs against a rubric. It is cheaper than human review but can be biased or inconsistent, so it is usually checked against human ratings.' },
  { id: 'mlflow-alias', term: 'MLflow alias', level: 'ai-llm-mlops', definition: 'A movable name, such as "production", that points to a specific registered model version in MLflow\'s model registry. Moving the alias promotes or rolls back a model without changing the code that loads it.' },
  { id: 'onnx', term: 'ONNX', level: 'ai-llm-mlops', definition: 'Open Neural Network Exchange: a common file format for trained models that lets a model built in one framework run in other tools and runtimes. Not every model feature converts cleanly.' },
  { id: 'pickle', term: 'Pickle (code-execution risk)', level: 'ai-llm-mlops', definition: 'Python\'s built-in way of saving objects to a file. Loading a pickle file can run arbitrary code hidden in it, so only load pickles from sources you fully trust.' },
  { id: 'pipeline-parallelism', term: 'Pipeline parallelism', level: 'ai-llm-mlops', definition: 'Splitting a model into consecutive chunks of layers, each on a different GPU, and passing data through them like an assembly line. Splitting each batch into smaller pieces keeps the GPUs from sitting idle.' },
  { id: 'point-in-time-join', term: 'Point-in-time-correct join', level: 'ai-llm-mlops', definition: 'Combining data so each training example only uses information that was known at that example\'s timestamp. This avoids leaking future information into training, which would make a model look better than it really is.' },
  { id: 'population-based-training', term: 'Population-based training', level: 'ai-llm-mlops', definition: 'Training many models at once and, during training, copying settings from the better ones to the worse ones with small random changes. It adjusts hyperparameters as training goes rather than fixing them upfront.' },
  { id: 'prefill', term: 'Prefill', level: 'ai-llm-mlops', definition: 'The first phase of answering, where a language model reads the whole prompt in one pass before generating anything. It is usually limited by computation and determines how long you wait for the first token.' },
  { id: 'prompt-caching', term: 'Prompt caching', level: 'ai-llm-mlops', definition: 'Reusing the already-processed beginning of a prompt when later requests start with the same text. It lowers latency and often cost for repeated long instructions or documents.' },
  { id: 'psi', term: 'PSI', level: 'ai-llm-mlops', definition: 'Population Stability Index: a single number that summarizes how much a feature\'s distribution has shifted between two periods. Larger values mean larger shifts, and teams commonly pick their own alert thresholds.' },
  { id: 'quantization', term: 'Quantization', level: 'ai-llm-mlops', definition: 'Storing a model\'s numbers with fewer bits, for example 8-bit or 4-bit instead of 16-bit. The model becomes smaller and faster, usually with some loss of accuracy.' },
  { id: 'rag', term: 'RAG', level: 'ai-llm-mlops', definition: 'Retrieval-Augmented Generation: looking up relevant documents first and giving them to the language model along with the question. It lets the model answer using information it was not trained on.' },
  { id: 'safetensors', term: 'Safetensors', level: 'ai-llm-mlops', definition: 'A file format for storing model weights that holds only numbers and cannot carry executable code. It is safer to load than pickle and is quick to read.' },
  { id: 'semantic-caching', term: 'Semantic caching', level: 'ai-llm-mlops', definition: 'Reusing a previous answer when a new question means roughly the same thing, found by comparing embeddings rather than exact text. It saves calls but can return a wrong answer if two questions only look similar.' },
  { id: 'speculative-decoding', term: 'Speculative decoding', level: 'ai-llm-mlops', definition: 'A small, fast model guesses several upcoming tokens and the large model checks them all at once, keeping the ones it agrees with. Output quality stays the same while generation gets faster.' },
  { id: 'surrogate-model', term: 'Surrogate model', level: 'ai-llm-mlops', definition: 'A cheap model that predicts how an expensive experiment, such as a full training run, will turn out. Tuning methods use it to decide which settings to try next.' },
  { id: 'tensor-parallelism', term: 'Tensor parallelism', level: 'ai-llm-mlops', definition: 'Splitting the large math operations inside a single layer across several GPUs, which combine their partial results. It needs fast connections between the GPUs.' },
  { id: 'top-p', term: 'top_p', level: 'ai-llm-mlops', definition: 'A text-generation setting that limits the model to the smallest set of most likely next tokens whose probabilities add up to p, then samples from that set. Lower values make output more predictable.' },
  { id: 'training-serving-skew', term: 'Training/serving skew', level: 'ai-llm-mlops', definition: 'A mismatch between how data is prepared when a model is trained and how it is prepared when the model is used live. The model then sees inputs unlike what it learned from and performs worse than testing suggested.' },
  { id: 'ttft', term: 'TTFT', level: 'ai-llm-mlops', definition: 'Time to first token: how long a user waits between sending a prompt and seeing the first piece of the answer. It is mostly driven by queueing and prefill.' },
  { id: 'vector-index', term: 'Vector index', level: 'ai-llm-mlops', definition: 'A data structure that finds the stored embeddings closest to a query embedding without checking every one. Many indexes are approximate, trading a little accuracy for much greater speed.' },
  { id: 'zero', term: 'ZeRO', level: 'ai-llm-mlops', definition: 'Zero Redundancy Optimizer: a family of techniques that splits optimizer state, gradients and optionally the weights across GPUs instead of copying them to each one. It reduces memory per GPU and is the idea behind FSDP-style training.' },
];

export const TERMS: TermDefinition[] = [
  ...SHARED_TERMS,
  ...DEVOPS_TERMS,
  ...AI_LLM_MLOPS_TERMS,
];

/** Overview shows shared terms only; each specialization adds its own on top. */
export function getTermsForLevel(level: TermPageLevel): TermDefinition[] {
  return TERMS.filter(
    (termDefinition) =>
      termDefinition.level === 'shared' || termDefinition.level === level,
  );
}
